package org.omg.ManagedGenericIRPConstDefs;

/**
* org.omg.ManagedGenericIRPConstDefs/ShortTypeOptHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.ManagedGenericIRPConstDefs.idl
* jueves 5 de septiembre de 2019 02:00:53 AM CDT
*/

public final class ShortTypeOptHolder implements org.omg.CORBA.portable.Streamable
{
  public ShortTypeOpt value = null;

  public ShortTypeOptHolder ()
  {
  }

  public ShortTypeOptHolder (ShortTypeOpt initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ShortTypeOptHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ShortTypeOptHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ShortTypeOptHelper.type ();
  }

}
