package org.omg.ManagedGenericIRPConstDefs;


/**
* org.omg.ManagedGenericIRPConstDefs/Signal.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.ManagedGenericIRPConstDefs.idl
* jueves 5 de septiembre de 2019 02:00:52 AM CDT
*/

public class Signal implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static Signal[] __array = new Signal [__size];

  public static final int _OK = 0;
  public static final Signal OK = new Signal(_OK);
  public static final int _FAILURE = 1;
  public static final Signal FAILURE = new Signal(_FAILURE);
  public static final int _PARTIALFAILURE = 2;
  public static final Signal PARTIALFAILURE = new Signal(_PARTIALFAILURE);

  public int value ()
  {
    return __value;
  }

  public static Signal from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected Signal (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class Signal
