package org.omg.StateManagementIRPOptConstDefs;


/**
* org.omg.StateManagementIRPOptConstDefs/AlarmStatusTypeOpt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.StateManagementIRPOptConstDefs.idl
* jueves 5 de septiembre de 2019 02:21:32 AM CDT
*/

public final class AlarmStatusTypeOpt implements org.omg.CORBA.portable.IDLEntity
{
  private org.omg.StateManagementIRPConstDefs.AlarmStatusValues[] ___alarm_status;
  private boolean __discriminator;
  private boolean __uninitialized = true;

  public AlarmStatusTypeOpt ()
  {
  }

  public boolean discriminator ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    return __discriminator;
  }

  public org.omg.StateManagementIRPConstDefs.AlarmStatusValues[] alarm_status ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifyalarm_status (__discriminator);
    return ___alarm_status;
  }

  public void alarm_status (org.omg.StateManagementIRPConstDefs.AlarmStatusValues[] value)
  {
    __discriminator = true;
    ___alarm_status = value;
    __uninitialized = false;
  }

  public void alarm_status (boolean discriminator, org.omg.StateManagementIRPConstDefs.AlarmStatusValues[] value)
  {
    verifyalarm_status (discriminator);
    __discriminator = discriminator;
    ___alarm_status = value;
    __uninitialized = false;
  }

  private void verifyalarm_status (boolean discriminator)
  {
    if (discriminator != true)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public void _default ()
  {
    __discriminator = false;
    __uninitialized = false;
  }

  public void _default (boolean discriminator)
  {
    verifyDefault( discriminator ) ;
    __discriminator = discriminator ;
    __uninitialized = false;
  }

  private void verifyDefault (boolean discriminator)
  {
    if ( discriminator )
        throw new org.omg.CORBA.BAD_OPERATION();
  }

} // class AlarmStatusTypeOpt
