package org.omg.StateManagementIRPOptConstDefs;


/**
* org.omg.StateManagementIRPOptConstDefs/ControlStatusTypeOpt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.StateManagementIRPOptConstDefs.idl
* jueves 5 de septiembre de 2019 02:21:32 AM CDT
*/

public final class ControlStatusTypeOpt implements org.omg.CORBA.portable.IDLEntity
{
  private org.omg.StateManagementIRPConstDefs.ControlStatusValues[] ___control_status;
  private boolean __discriminator;
  private boolean __uninitialized = true;

  public ControlStatusTypeOpt ()
  {
  }

  public boolean discriminator ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    return __discriminator;
  }

  public org.omg.StateManagementIRPConstDefs.ControlStatusValues[] control_status ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifycontrol_status (__discriminator);
    return ___control_status;
  }

  public void control_status (org.omg.StateManagementIRPConstDefs.ControlStatusValues[] value)
  {
    __discriminator = true;
    ___control_status = value;
    __uninitialized = false;
  }

  public void control_status (boolean discriminator, org.omg.StateManagementIRPConstDefs.ControlStatusValues[] value)
  {
    verifycontrol_status (discriminator);
    __discriminator = discriminator;
    ___control_status = value;
    __uninitialized = false;
  }

  private void verifycontrol_status (boolean discriminator)
  {
    if (discriminator != true)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public void _default ()
  {
    __discriminator = false;
    __uninitialized = false;
  }

  public void _default (boolean discriminator)
  {
    verifyDefault( discriminator ) ;
    __discriminator = discriminator ;
    __uninitialized = false;
  }

  private void verifyDefault (boolean discriminator)
  {
    if ( discriminator )
        throw new org.omg.CORBA.BAD_OPERATION();
  }

} // class ControlStatusTypeOpt
