package org.omg.StateManagementIRPOptConstDefs;


/**
* org.omg.StateManagementIRPOptConstDefs/UsageStateTypeOpt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.StateManagementIRPOptConstDefs.idl
* jueves 5 de septiembre de 2019 02:21:32 AM CDT
*/

public final class UsageStateTypeOpt implements org.omg.CORBA.portable.IDLEntity
{
  private org.omg.StateManagementIRPConstDefs.UsageState ___usage_state;
  private boolean __discriminator;
  private boolean __uninitialized = true;

  public UsageStateTypeOpt ()
  {
  }

  public boolean discriminator ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    return __discriminator;
  }

  public org.omg.StateManagementIRPConstDefs.UsageState usage_state ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifyusage_state (__discriminator);
    return ___usage_state;
  }

  public void usage_state (org.omg.StateManagementIRPConstDefs.UsageState value)
  {
    __discriminator = true;
    ___usage_state = value;
    __uninitialized = false;
  }

  public void usage_state (boolean discriminator, org.omg.StateManagementIRPConstDefs.UsageState value)
  {
    verifyusage_state (discriminator);
    __discriminator = discriminator;
    ___usage_state = value;
    __uninitialized = false;
  }

  private void verifyusage_state (boolean discriminator)
  {
    if (discriminator != true)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public void _default ()
  {
    __discriminator = false;
    __uninitialized = false;
  }

  public void _default (boolean discriminator)
  {
    verifyDefault( discriminator ) ;
    __discriminator = discriminator ;
    __uninitialized = false;
  }

  private void verifyDefault (boolean discriminator)
  {
    if ( discriminator )
        throw new org.omg.CORBA.BAD_OPERATION();
  }

} // class UsageStateTypeOpt
