package org.omg.KernelCmIRPSystem;


/**
* org.omg.KernelCmIRPSystem/GetKernelCMIRPVersionsException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.KernelCmIRPSystem.idl
* jueves 5 de septiembre de 2019 02:19:42 AM CDT
*/

public final class GetKernelCMIRPVersionsException extends org.omg.CORBA.UserException
{
  public String reason = null;

  public GetKernelCMIRPVersionsException ()
  {
    super(GetKernelCMIRPVersionsExceptionHelper.id());
  } // ctor

  public GetKernelCMIRPVersionsException (String _reason)
  {
    super(GetKernelCMIRPVersionsExceptionHelper.id());
    reason = _reason;
  } // ctor


  public GetKernelCMIRPVersionsException (String $reason, String _reason)
  {
    super(GetKernelCMIRPVersionsExceptionHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class GetKernelCMIRPVersionsException
