package org.omg.CosEventComm;


/**
* org.omg.CosEventComm/PullConsumer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CosEventComm.idl
* jueves 5 de septiembre de 2019 02:15:44 AM CDT
*/

public interface PullConsumer extends PullConsumerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PullConsumer
