package org.omg.CosEventComm;


/**
* org.omg.CosEventComm/PushSupplier.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CosEventComm.idl
* jueves 5 de septiembre de 2019 02:15:44 AM CDT
*/

public interface PushSupplier extends PushSupplierOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PushSupplier
