package org.omg.BasicCmIRPSystem;


/**
* org.omg.BasicCmIRPSystem/BasicCmInformationIteratorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BasicCMIRPSystem.idl
* jueves 5 de septiembre de 2019 02:15:11 AM CDT
*/


/**
     The BasicCmInformationIterator is used to iterate through a snapshot of 
      Managed Object Information when IRPManager invokes find_managed_objects.
      IRPManager uses it to pace the return of Managed Object Information.

     IRPAgent controls the life-cycle of the iterator. However, a destroy
      operation is provided to handle the case where IRPManager wants to stop
      the iteration procedure before reaching the last iteration.
     */
public interface BasicCmInformationIteratorOperations 
{

  /**
        This method returns between 1 and "how_many" Managed Object information.
         The IRPAgent may return less than "how_many" items even if there are
         more items to return. "how_many" must be non-zero. Return TRUE if there
         may be more Managed Object information to return. Return FALSE if there
         are no more Managed Object information to be returned. 

         If FALSE is returned, the IRPAgent will automatically destroy the
          iterator.

         @parm how_many how many elements to return in the "fetchedElements" out
          parameter.
         @parm fetchedElements the elements.
         @returns A boolean indicating if any elements are returned. 
          "fetchedElements" is empty when the BasicCmInformationIterator is
          empty.
        */
  boolean next_basicCmInformations(short how_many, org.omg.BasicCMIRPConstDefs.ResultSetHolder fetchedElements) throws NextBasicCmInformations, org.omg.ManagedGenericIRPSystem.InvalidParameter, org.omg.ManagedGenericIRPSystem.OperationNotSupported;

  /**
        This method destroys the iterator.
        */
  void destroy() throws DestroyException, org.omg.ManagedGenericIRPSystem.OperationNotSupported;
} // interface BasicCmInformationIteratorOperations
