package org.omg.BasicCmIRPSystem;

/**
* org.omg.BasicCmIRPSystem/CreateManagedObjectHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BasicCMIRPSystem.idl
* jueves 5 de septiembre de 2019 02:15:11 AM CDT
*/

public final class CreateManagedObjectHolder implements org.omg.CORBA.portable.Streamable
{
  public CreateManagedObject value = null;

  public CreateManagedObjectHolder ()
  {
  }

  public CreateManagedObjectHolder (CreateManagedObject initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CreateManagedObjectHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CreateManagedObjectHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CreateManagedObjectHelper.type ();
  }

}
