package org.omg.BasicCmIRPSystem;


/**
* org.omg.BasicCmIRPSystem/CreateNotAllowed.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BasicCMIRPSystem.idl
* jueves 5 de septiembre de 2019 02:15:11 AM CDT
*/

public final class CreateNotAllowed extends org.omg.CORBA.UserException
{

  public CreateNotAllowed ()
  {
    super(CreateNotAllowedHelper.id());
  } // ctor


  public CreateNotAllowed (String $reason)
  {
    super(CreateNotAllowedHelper.id() + "  " + $reason);
  } // ctor

} // class CreateNotAllowed
