package org.omg.BasicCmIRPSystem;


/**
* org.omg.BasicCmIRPSystem/DeleteResultIteratorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BasicCMIRPSystem.idl
* jueves 5 de septiembre de 2019 02:15:12 AM CDT
*/


/**
     The DeleteResultIterator is used to iterate through the list of deleted MOs
      when IRPManager invokes method "delete_managed_objects".
      IRPManager uses it to pace the return of Managed Object Information.

     IRPAgent controls the life-cycle of the iterator. However, a destroy
      operation is provided to handle the case where IRPManager wants to stop
      the iteration procedure before reaching the last iteration.
     */
public interface DeleteResultIteratorOperations  extends BasicCmInformationIteratorOperations
{

  /**
        This method returns between 0 and "how_many" deletion errors. The
         IRPAgent may return less than "how_many" items even if there are more
         items to return. "how_many" must be non-zero. Return TRUE if there are
         more deletion errors to return. Return FALSE if there are no more
         deletion errors to be returned.

         If FALSE is returned and last call to inherited method
         "next_basicCmInformations" also returned FALSE (i.e. no more Managed
         Object information to be returned), the IRPAgent will automatically
         destroy the iterator.

         @parm how_many: how many deletion errors to return in the
          "fetchedDeleteErrors" out parameter.
         @parm fetchedDeleteErrors: the deletion errors.
         @returns: a boolean indicating if any deletion errors are returned.
        */
  boolean next_deleteErrors(short how_many, org.omg.BasicCMIRPConstDefs.DeleteErrorSeqHolder fetchedDeleteErrors) throws NextDeleteErrors, org.omg.ManagedGenericIRPSystem.InvalidParameter;
} // interface DeleteResultIteratorOperations
