package org.omg.BasicCmIRPSystem;


/**
* org.omg.BasicCmIRPSystem/DuplicateMO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BasicCMIRPSystem.idl
* jueves 5 de septiembre de 2019 02:15:10 AM CDT
*/

public final class DuplicateMO extends org.omg.CORBA.UserException
{

  public DuplicateMO ()
  {
    super(DuplicateMOHelper.id());
  } // ctor


  public DuplicateMO (String $reason)
  {
    super(DuplicateMOHelper.id() + "  " + $reason);
  } // ctor

} // class DuplicateMO
