package org.omg.BasicCmIRPSystem;

/**
* org.omg.BasicCmIRPSystem/FilterComplexityLimitHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BasicCMIRPSystem.idl
* jueves 5 de septiembre de 2019 02:15:10 AM CDT
*/

public final class FilterComplexityLimitHolder implements org.omg.CORBA.portable.Streamable
{
  public FilterComplexityLimit value = null;

  public FilterComplexityLimitHolder ()
  {
  }

  public FilterComplexityLimitHolder (FilterComplexityLimit initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FilterComplexityLimitHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FilterComplexityLimitHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FilterComplexityLimitHelper.type ();
  }

}
