package org.omg.BasicCmIRPSystem;


/**
* org.omg.BasicCmIRPSystem/FilterComplexityLimit.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BasicCMIRPSystem.idl
* jueves 5 de septiembre de 2019 02:15:10 AM CDT
*/

public final class FilterComplexityLimit extends org.omg.CORBA.UserException
{
  public String reason = null;

  public FilterComplexityLimit ()
  {
    super(FilterComplexityLimitHelper.id());
  } // ctor

  public FilterComplexityLimit (String _reason)
  {
    super(FilterComplexityLimitHelper.id());
    reason = _reason;
  } // ctor


  public FilterComplexityLimit (String $reason, String _reason)
  {
    super(FilterComplexityLimitHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class FilterComplexityLimit
