package org.omg.BasicCmIRPSystem;


/**
* org.omg.BasicCmIRPSystem/IllegalDNFormatException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BasicCMIRPSystem.idl
* jueves 5 de septiembre de 2019 02:15:10 AM CDT
*/

public final class IllegalDNFormatException extends org.omg.CORBA.UserException
{
  public String reason = null;

  public IllegalDNFormatException ()
  {
    super(IllegalDNFormatExceptionHelper.id());
  } // ctor

  public IllegalDNFormatException (String _reason)
  {
    super(IllegalDNFormatExceptionHelper.id());
    reason = _reason;
  } // ctor


  public IllegalDNFormatException (String $reason, String _reason)
  {
    super(IllegalDNFormatExceptionHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class IllegalDNFormatException
