package org.omg.BasicCmIRPSystem;

/**
* org.omg.BasicCmIRPSystem/IllegalFilterFormatExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BasicCMIRPSystem.idl
* jueves 5 de septiembre de 2019 02:15:10 AM CDT
*/

public final class IllegalFilterFormatExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public IllegalFilterFormatException value = null;

  public IllegalFilterFormatExceptionHolder ()
  {
  }

  public IllegalFilterFormatExceptionHolder (IllegalFilterFormatException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IllegalFilterFormatExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IllegalFilterFormatExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IllegalFilterFormatExceptionHelper.type ();
  }

}
