package org.omg.BasicCmIRPSystem;

/**
* org.omg.BasicCmIRPSystem/NextModifyErrorsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BasicCMIRPSystem.idl
* jueves 5 de septiembre de 2019 02:15:11 AM CDT
*/

public final class NextModifyErrorsHolder implements org.omg.CORBA.portable.Streamable
{
  public NextModifyErrors value = null;

  public NextModifyErrorsHolder ()
  {
  }

  public NextModifyErrorsHolder (NextModifyErrors initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = NextModifyErrorsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    NextModifyErrorsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return NextModifyErrorsHelper.type ();
  }

}
