package org.omg.BasicCmIRPSystem;


/**
* org.omg.BasicCmIRPSystem/NextBasicCmInformations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BasicCMIRPSystem.idl
* jueves 5 de septiembre de 2019 02:15:11 AM CDT
*/

public final class NextBasicCmInformations extends org.omg.CORBA.UserException
{
  public String reason = null;

  public NextBasicCmInformations ()
  {
    super(NextBasicCmInformationsHelper.id());
  } // ctor

  public NextBasicCmInformations (String _reason)
  {
    super(NextBasicCmInformationsHelper.id());
    reason = _reason;
  } // ctor


  public NextBasicCmInformations (String $reason, String _reason)
  {
    super(NextBasicCmInformationsHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class NextBasicCmInformations
