package org.omg.BasicCmIRPSystem;

/**
* org.omg.BasicCmIRPSystem/NextDeleteErrorsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BasicCMIRPSystem.idl
* jueves 5 de septiembre de 2019 02:15:11 AM CDT
*/

public final class NextDeleteErrorsHolder implements org.omg.CORBA.portable.Streamable
{
  public NextDeleteErrors value = null;

  public NextDeleteErrorsHolder ()
  {
  }

  public NextDeleteErrorsHolder (NextDeleteErrors initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = NextDeleteErrorsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    NextDeleteErrorsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return NextDeleteErrorsHelper.type ();
  }

}
