package org.omg.BasicCmIRPSystem;

/**
* org.omg.BasicCmIRPSystem/UndefinedMOExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BasicCMIRPSystem.idl
* jueves 5 de septiembre de 2019 02:15:10 AM CDT
*/

public final class UndefinedMOExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public UndefinedMOException value = null;

  public UndefinedMOExceptionHolder ()
  {
  }

  public UndefinedMOExceptionHolder (UndefinedMOException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = UndefinedMOExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    UndefinedMOExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return UndefinedMOExceptionHelper.type ();
  }

}
