package org.omg.CosNotifyFilter;


/**
* org.omg.CosNotifyFilter/FilterAdminOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CosNotifyFilter.idl
* jueves 5 de septiembre de 2019 02:16:38 AM CDT
*/

public interface FilterAdminOperations 
{
  int add_filter(Filter new_filter);
  void remove_filter(int filter) throws FilterNotFound;
  Filter get_filter(int filter) throws FilterNotFound;
  int[] get_all_filters();
  void remove_all_filters();
} // interface FilterAdminOperations
