package org.omg.CosNotifyFilter;


/**
* org.omg.CosNotifyFilter/InvalidGrammar.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CosNotifyFilter.idl
* jueves 5 de septiembre de 2019 02:16:37 AM CDT
*/

public final class InvalidGrammar extends org.omg.CORBA.UserException
{

  public InvalidGrammar ()
  {
    super(InvalidGrammarHelper.id());
  } // ctor


  public InvalidGrammar (String $reason)
  {
    super(InvalidGrammarHelper.id() + "  " + $reason);
  } // ctor

} // class InvalidGrammar
