package org.omg.CosNotifyFilter;

/**
* org.omg.CosNotifyFilter/InvalidValueHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CosNotifyFilter.idl
* jueves 5 de septiembre de 2019 02:16:37 AM CDT
*/

public final class InvalidValueHolder implements org.omg.CORBA.portable.Streamable
{
  public InvalidValue value = null;

  public InvalidValueHolder ()
  {
  }

  public InvalidValueHolder (InvalidValue initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = InvalidValueHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    InvalidValueHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return InvalidValueHelper.type ();
  }

}
