package org.omg.CosNotifyFilter;


/**
* org.omg.CosNotifyFilter/InvalidValue.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CosNotifyFilter.idl
* jueves 5 de septiembre de 2019 02:16:37 AM CDT
*/

public final class InvalidValue extends org.omg.CORBA.UserException
{
  public ConstraintExp constr = null;
  public org.omg.CORBA.Any value = null;

  public InvalidValue ()
  {
    super(InvalidValueHelper.id());
  } // ctor

  public InvalidValue (ConstraintExp _constr, org.omg.CORBA.Any _value)
  {
    super(InvalidValueHelper.id());
    constr = _constr;
    value = _value;
  } // ctor


  public InvalidValue (String $reason, ConstraintExp _constr, org.omg.CORBA.Any _value)
  {
    super(InvalidValueHelper.id() + "  " + $reason);
    constr = _constr;
    value = _value;
  } // ctor

} // class InvalidValue
