package org.omg.CosNotifyFilter;


/**
* org.omg.CosNotifyFilter/MappingConstraintInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CosNotifyFilter.idl
* jueves 5 de septiembre de 2019 02:16:37 AM CDT
*/

public final class MappingConstraintInfo implements org.omg.CORBA.portable.IDLEntity
{
  public ConstraintExp constraint_expression = null;
  public int constraint_id = (int)0;
  public org.omg.CORBA.Any value = null;

  public MappingConstraintInfo ()
  {
  } // ctor

  public MappingConstraintInfo (ConstraintExp _constraint_expression, int _constraint_id, org.omg.CORBA.Any _value)
  {
    constraint_expression = _constraint_expression;
    constraint_id = _constraint_id;
    value = _value;
  } // ctor

} // class MappingConstraintInfo
