package org.omg.CosNotifyFilter;


/**
* org.omg.CosNotifyFilter/MappingFilterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CosNotifyFilter.idl
* jueves 5 de septiembre de 2019 02:16:37 AM CDT
*/


// Filter
public interface MappingFilterOperations 
{
  String constraint_grammar();
  org.omg.CORBA.TypeCode value_type();
  org.omg.CORBA.Any default_value();
  MappingConstraintInfo[] add_mapping_constraints(MappingConstraintPair[] pair_list) throws InvalidConstraint, InvalidValue;
  void modify_mapping_constraints(int[] del_list, MappingConstraintInfo[] modify_list) throws InvalidConstraint, InvalidValue, ConstraintNotFound;
  MappingConstraintInfo[] get_mapping_constraints(int[] id_list) throws ConstraintNotFound;
  MappingConstraintInfo[] get_all_mapping_constraints();
  void remove_all_mapping_constraints();
  void destroy();
  boolean match(org.omg.CORBA.Any filterable_data, org.omg.CORBA.AnyHolder result_to_set) throws UnsupportedFilterableData;
  boolean match_structured(org.omg.CosNotification.StructuredEvent filterable_data, org.omg.CORBA.AnyHolder result_to_set) throws UnsupportedFilterableData;
  boolean match_typed(org.omg.CosNotification.Property[] filterable_data, org.omg.CORBA.AnyHolder result_to_set) throws UnsupportedFilterableData;
} // interface MappingFilterOperations
