package org.omg.AlarmIRPSystem;


/**
* org.omg.AlarmIRPSystem/GetAlarmCount.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.AlarmIRPSystem.idl
* jueves 5 de septiembre de 2019 01:52:14 AM CDT
*/

public final class GetAlarmCount extends org.omg.CORBA.UserException
{
  public String reason = null;

  public GetAlarmCount ()
  {
    super(GetAlarmCountHelper.id());
  } // ctor

  public GetAlarmCount (String _reason)
  {
    super(GetAlarmCountHelper.id());
    reason = _reason;
  } // ctor


  public GetAlarmCount (String $reason, String _reason)
  {
    super(GetAlarmCountHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class GetAlarmCount
