package org.omg.AlarmIRPConstDefs;

/**
* org.omg.AlarmIRPConstDefs/AckStateHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.AlarmIRPConstDefs.idl
* jueves 5 de septiembre de 2019 01:59:42 AM CDT
*/


/*
   This block identifies the acknowledgement state of a reported alarm.
   */
public final class AckStateHolder implements org.omg.CORBA.portable.Streamable
{
  public AckState value = null;

  public AckStateHolder ()
  {
  }

  public AckStateHolder (AckState initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AckStateHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AckStateHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AckStateHelper.type ();
  }

}
