package org.omg.AlarmIRPConstDefs;

/**
* org.omg.AlarmIRPConstDefs/AlarmInformationIdAndSevHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.AlarmIRPConstDefs.idl
* jueves 5 de septiembre de 2019 01:59:43 AM CDT
*/

public final class AlarmInformationIdAndSevHolder implements org.omg.CORBA.portable.Streamable
{
  public AlarmInformationIdAndSev value = null;

  public AlarmInformationIdAndSevHolder ()
  {
  }

  public AlarmInformationIdAndSevHolder (AlarmInformationIdAndSev initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AlarmInformationIdAndSevHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AlarmInformationIdAndSevHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AlarmInformationIdAndSevHelper.type ();
  }

}
