package org.omg.AlarmIRPConstDefs;


/**
* org.omg.AlarmIRPConstDefs/AlarmListAlignmentRequirementTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.AlarmIRPConstDefs.idl
* jueves 5 de septiembre de 2019 01:59:43 AM CDT
*/


/*
   It indicates if the AlarmList alignment is required.
   */
abstract public class AlarmListAlignmentRequirementTypeHelper
{
  private static String  _id = "IDL:3gppsa5.org/AlarmIRPConstDefs/AlarmListAlignmentRequirementType:1.0";

  public static void insert (org.omg.CORBA.Any a, AlarmListAlignmentRequirementType that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static AlarmListAlignmentRequirementType extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (AlarmListAlignmentRequirementTypeHelper.id (), "AlarmListAlignmentRequirementType", new String[] { "REQUIRED", "NOTREQUIRED"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static AlarmListAlignmentRequirementType read (org.omg.CORBA.portable.InputStream istream)
  {
    return AlarmListAlignmentRequirementType.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, AlarmListAlignmentRequirementType value)
  {
    ostream.write_long (value.value ());
  }

}
