package org.omg.AlarmIRPConstDefs;


/**
* org.omg.AlarmIRPConstDefs/AlarmInformationIdAndSev.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.AlarmIRPConstDefs.idl
* jueves 5 de septiembre de 2019 01:59:43 AM CDT
*/

public final class AlarmInformationIdAndSev implements org.omg.CORBA.portable.IDLEntity
{
  public String alarm_information_reference = null;
  public org.omg.ManagedGenericIRPConstDefs.ShortTypeOpt perceived_severity = null;

  public AlarmInformationIdAndSev ()
  {
  } // ctor

  public AlarmInformationIdAndSev (String _alarm_information_reference, org.omg.ManagedGenericIRPConstDefs.ShortTypeOpt _perceived_severity)
  {
    alarm_information_reference = _alarm_information_reference;
    perceived_severity = _perceived_severity;
  } // ctor

} // class AlarmInformationIdAndSev
