package org.omg.AlarmIRPConstDefs;

/**
* org.omg.AlarmIRPConstDefs/AttributeValueTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.AlarmIRPConstDefs.idl
* jueves 5 de septiembre de 2019 01:59:43 AM CDT
*/

public final class AttributeValueTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public AttributeValueType value = null;

  public AttributeValueTypeHolder ()
  {
  }

  public AttributeValueTypeHolder (AttributeValueType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AttributeValueTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AttributeValueTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AttributeValueTypeHelper.type ();
  }

}
