package org.omg.AlarmIRPConstDefs;


/**
* org.omg.AlarmIRPConstDefs/AttributeValueType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.AlarmIRPConstDefs.idl
* jueves 5 de septiembre de 2019 01:59:43 AM CDT
*/

public final class AttributeValueType implements org.omg.CORBA.portable.IDLEntity
{
  public String attribute_name = null;
  public org.omg.CORBA.Any value = null;

  public AttributeValueType ()
  {
  } // ctor

  public AttributeValueType (String _attribute_name, org.omg.CORBA.Any _value)
  {
    attribute_name = _attribute_name;
    value = _value;
  } // ctor

} // class AttributeValueType
