package org.omg.AlarmIRPConstDefs;


import org.omg.TimeBase.UtcT;

/**
* org.omg.AlarmIRPConstDefs/Comment.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.AlarmIRPConstDefs.idl
* jueves 5 de septiembre de 2019 01:59:42 AM CDT
*/

public final class Comment implements org.omg.CORBA.portable.IDLEntity
{
  public UtcT comment_time = null;
  public String comment_text = null;
  public String user_id = null;
  public String system_id = null;

  public Comment ()
  {
  } // ctor

  public Comment (UtcT _comment_time, String _comment_text, String _user_id, String _system_id)
  {
    comment_time = _comment_time;
    comment_text = _comment_text;
    user_id = _user_id;
    system_id = _system_id;
  } // ctor

} // class Comment
