package org.omg.AlarmIRPConstDefs;


/**
* org.omg.AlarmIRPConstDefs/CommentSetHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.AlarmIRPConstDefs.idl
* jueves 5 de septiembre de 2019 01:59:42 AM CDT
*/


/*
   Defines a set of comments which are placed in the COMMENTS attribute
   of a structured event.
   */
public final class CommentSetHolder implements org.omg.CORBA.portable.Streamable
{
  public Comment value[] = null;

  public CommentSetHolder ()
  {
  }

  public CommentSetHolder (Comment[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CommentSetHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CommentSetHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CommentSetHelper.type ();
  }

}
