package org.omg.AlarmIRPConstDefs;

/**
* org.omg.AlarmIRPConstDefs/CommentHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.AlarmIRPConstDefs.idl
* jueves 5 de septiembre de 2019 01:59:42 AM CDT
*/

public final class CommentHolder implements org.omg.CORBA.portable.Streamable
{
  public Comment value = null;

  public CommentHolder ()
  {
  }

  public CommentHolder (Comment initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CommentHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CommentHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CommentHelper.type ();
  }

}
