package org.omg.AlarmIRPConstDefs;


/**
* org.omg.AlarmIRPConstDefs/NotificationTypePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.AlarmIRPConstDefs.idl
* jueves 5 de septiembre de 2019 01:59:42 AM CDT
*/


/*
   This block identifies the notification types defined by this
   Alarm IRP version.
   */
public abstract class NotificationTypePOA extends org.omg.PortableServer.Servant
 implements NotificationTypeOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    Integer __method = (Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:3gppsa5.org/AlarmIRPConstDefs/NotificationType:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public NotificationType _this() 
  {
    return NotificationTypeHelper.narrow(
    super._this_object());
  }

  public NotificationType _this(org.omg.CORBA.ORB orb) 
  {
    return NotificationTypeHelper.narrow(
    super._this_object(orb));
  }


} // class NotificationTypePOA
