package org.omg.AlarmIRPConstDefs;

/**
* org.omg.AlarmIRPConstDefs/ProbableCauseHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.AlarmIRPConstDefs.idl
* jueves 5 de septiembre de 2019 01:59:42 AM CDT
*/


/*
   This block identifies the probable cause of a reported alarm.
   */
public final class ProbableCauseHolder implements org.omg.CORBA.portable.Streamable
{
  public ProbableCause value = null;

  public ProbableCauseHolder ()
  {
  }

  public ProbableCauseHolder (ProbableCause initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ProbableCauseHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ProbableCauseHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ProbableCauseHelper.type ();
  }

}
