package org.omg.AlarmIRPConstDefs;


/**
* org.omg.AlarmIRPConstDefs/ThresholdIndicationTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.AlarmIRPConstDefs.idl
* jueves 5 de septiembre de 2019 01:59:43 AM CDT
*/


/*
   It indicates if the threshold crossed was in the up or down direction.
   */
abstract public class ThresholdIndicationTypeHelper
{
  private static String  _id = "IDL:3gppsa5.org/AlarmIRPConstDefs/ThresholdIndicationType:1.0";

  public static void insert (org.omg.CORBA.Any a, ThresholdIndicationType that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ThresholdIndicationType extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (ThresholdIndicationTypeHelper.id (), "ThresholdIndicationType", new String[] { "UP", "DOWN"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ThresholdIndicationType read (org.omg.CORBA.portable.InputStream istream)
  {
    return ThresholdIndicationType.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ThresholdIndicationType value)
  {
    ostream.write_long (value.value ());
  }

}
