package org.omg.AlarmIRPConstDefs;

/**
* org.omg.AlarmIRPConstDefs/ThresholdLevelIndTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.AlarmIRPConstDefs.idl
* jueves 5 de septiembre de 2019 01:59:43 AM CDT
*/

public final class ThresholdLevelIndTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public ThresholdLevelIndType value = null;

  public ThresholdLevelIndTypeHolder ()
  {
  }

  public ThresholdLevelIndTypeHolder (ThresholdLevelIndType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ThresholdLevelIndTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ThresholdLevelIndTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ThresholdLevelIndTypeHelper.type ();
  }

}
