package org.omg.GeranNetworkResourcesNRMDefs;


/**
* org.omg.GeranNetworkResourcesNRMDefs/BtsSiteMgrOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.GeranNetworkResourcesNRMDefs.idl
* jueves 5 de septiembre de 2019 02:19:22 AM CDT
*/


/**
       *  Definitions for MO class BtsSiteMgr
       */
public interface BtsSiteMgrOperations  extends org.omg.GenericNetworkResourcesNRMDefs.ManagedFunctionOperations
{
} // interface BtsSiteMgrOperations
