package org.omg.GeranNetworkResourcesNRMDefs;


/**
* org.omg.GeranNetworkResourcesNRMDefs/GsmCellHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.GeranNetworkResourcesNRMDefs.idl
* jueves 5 de septiembre de 2019 02:19:22 AM CDT
*/


/**
       *  Definitions for MO class GsmCell
       */
abstract public class GsmCellHelper
{
  private static String  _id = "IDL:3gppsa5.org/GeranNetworkResourcesNRMDefs/GsmCell:1.0";

  public static void insert (org.omg.CORBA.Any a, GsmCell that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static GsmCell extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (GsmCellHelper.id (), "GsmCell");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static GsmCell read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GsmCellStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, GsmCell value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static GsmCell narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof GsmCell)
      return (GsmCell)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _GsmCellStub stub = new _GsmCellStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static GsmCell unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof GsmCell)
      return (GsmCell)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _GsmCellStub stub = new _GsmCellStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
