package org.omg.GeranNetworkResourcesNRMDefs;


/**
* org.omg.GeranNetworkResourcesNRMDefs/GsmCell.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.GeranNetworkResourcesNRMDefs.idl
* jueves 5 de septiembre de 2019 02:19:22 AM CDT
*/


/**
       *  Definitions for MO class GsmCell
       */
public interface GsmCell extends GsmCellOperations, org.omg.GenericNetworkResourcesNRMDefs.ManagedFunction, org.omg.CORBA.portable.IDLEntity
{
  public static final String CLASS = "GsmCell";

  //
  public static final String gsmCellId = "gsmCellId";
  public static final String cellIdentity = "cellIdentity";
  public static final String cellAllocation = "cellAllocation";
  public static final String ncc = "ncc";
  public static final String bcc = "bcc";
  public static final String lac = "lac";
  public static final String mcc = "mcc";
  public static final String mnc = "mnc";
  public static final String rac = "rac";
  public static final String racc = "racc";
  public static final String tsc = "tsc";
  public static final String rxLevAccessMin = "rxLevAccessMin";
  public static final String msTxPwrMaxCCH = "msTxPwrMaxCCH";
  public static final String hoppingSequenceNumber = "hoppingSequenceNumber";
  public static final String plmnPermitted = "plmnPermitted";
} // interface GsmCell
