package org.omg.EPIRPConstDefs;

/**
* org.omg.EPIRPConstDefs/AttributeNameValueHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.EPIRPConstDefs.idl
* jueves 5 de septiembre de 2019 02:17:10 AM CDT
*/


/*
  Define the parameters specified in
  the notifyEpInfoChanges notification. 
  */
public final class AttributeNameValueHolder implements org.omg.CORBA.portable.Streamable
{
  public AttributeNameValue value = null;

  public AttributeNameValueHolder ()
  {
  }

  public AttributeNameValueHolder (AttributeNameValue initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AttributeNameValueHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AttributeNameValueHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AttributeNameValueHelper.type ();
  }

}
