package org.omg.EPIRPConstDefs;


/**
* org.omg.EPIRPConstDefs/AttributeNameValue.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.EPIRPConstDefs.idl
* jueves 5 de septiembre de 2019 02:17:10 AM CDT
*/


/*
  Define the parameters specified in
  the notifyEpInfoChanges notification. 
  */
public interface AttributeNameValue extends AttributeNameValueOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
  public static final String IRP_DN = "IRP_DN";
  public static final String CHANGE_MODE = "CHANGE_MODE";
  public static final String ADDITIONAL_TEXT = "ADDITIONAL_TEXT";
} // interface AttributeNameValue
