package org.omg.CosNotifyChannelAdmin;

/**
* org.omg.CosNotifyChannelAdmin/ConnectionAlreadyActiveHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CosNotifyChannelAdmin.idl
* jueves 5 de septiembre de 2019 02:16:14 AM CDT
*/

public final class ConnectionAlreadyActiveHolder implements org.omg.CORBA.portable.Streamable
{
  public ConnectionAlreadyActive value = null;

  public ConnectionAlreadyActiveHolder ()
  {
  }

  public ConnectionAlreadyActiveHolder (ConnectionAlreadyActive initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ConnectionAlreadyActiveHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ConnectionAlreadyActiveHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ConnectionAlreadyActiveHelper.type ();
  }

}
