package org.omg.CosNotifyChannelAdmin;


/**
* org.omg.CosNotifyChannelAdmin/EventChannelPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CosNotifyChannelAdmin.idl
* jueves 5 de septiembre de 2019 02:16:17 AM CDT
*/


// SupplierAdmin
public abstract class EventChannelPOA extends org.omg.PortableServer.Servant
 implements EventChannelOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_MyFactory", new Integer (0));
    _methods.put ("_get_default_consumer_admin", new Integer (1));
    _methods.put ("_get_default_supplier_admin", new Integer (2));
    _methods.put ("_get_default_filter_factory", new Integer (3));
    _methods.put ("new_for_consumers", new Integer (4));
    _methods.put ("new_for_suppliers", new Integer (5));
    _methods.put ("get_consumeradmin", new Integer (6));
    _methods.put ("get_supplieradmin", new Integer (7));
    _methods.put ("get_all_consumeradmins", new Integer (8));
    _methods.put ("get_all_supplieradmins", new Integer (9));
    _methods.put ("get_qos", new Integer (10));
    _methods.put ("set_qos", new Integer (11));
    _methods.put ("validate_qos", new Integer (12));
    _methods.put ("get_admin", new Integer (13));
    _methods.put ("set_admin", new Integer (14));
    _methods.put ("for_consumers", new Integer (15));
    _methods.put ("for_suppliers", new Integer (16));
    _methods.put ("destroy", new Integer (17));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    Integer __method = (Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // org.omg.CosNotifyChannelAdmin/EventChannel/_get_MyFactory
       {
         EventChannelFactory $result = null;
         $result = this.MyFactory ();
         out = $rh.createReply();
         EventChannelFactoryHelper.write (out, $result);
         break;
       }

       case 1:  // org.omg.CosNotifyChannelAdmin/EventChannel/_get_default_consumer_admin
       {
         ConsumerAdmin $result = null;
         $result = this.default_consumer_admin ();
         out = $rh.createReply();
         ConsumerAdminHelper.write (out, $result);
         break;
       }

       case 2:  // org.omg.CosNotifyChannelAdmin/EventChannel/_get_default_supplier_admin
       {
         SupplierAdmin $result = null;
         $result = this.default_supplier_admin ();
         out = $rh.createReply();
         SupplierAdminHelper.write (out, $result);
         break;
       }

       case 3:  // org.omg.CosNotifyChannelAdmin/EventChannel/_get_default_filter_factory
       {
         org.omg.CosNotifyFilter.FilterFactory $result = null;
         $result = this.default_filter_factory ();
         out = $rh.createReply();
         org.omg.CosNotifyFilter.FilterFactoryHelper.write (out, $result);
         break;
       }

       case 4:  // org.omg.CosNotifyChannelAdmin/EventChannel/new_for_consumers
       {
         InterFilterGroupOperator op = InterFilterGroupOperatorHelper.read (in);
         org.omg.CORBA.IntHolder id = new org.omg.CORBA.IntHolder ();
         ConsumerAdmin $result = null;
         $result = this.new_for_consumers (op, id);
         out = $rh.createReply();
         ConsumerAdminHelper.write (out, $result);
         AdminIDHelper.write (out, id.value);
         break;
       }

       case 5:  // org.omg.CosNotifyChannelAdmin/EventChannel/new_for_suppliers
       {
         InterFilterGroupOperator op = InterFilterGroupOperatorHelper.read (in);
         org.omg.CORBA.IntHolder id = new org.omg.CORBA.IntHolder ();
         SupplierAdmin $result = null;
         $result = this.new_for_suppliers (op, id);
         out = $rh.createReply();
         SupplierAdminHelper.write (out, $result);
         AdminIDHelper.write (out, id.value);
         break;
       }

       case 6:  // org.omg.CosNotifyChannelAdmin/EventChannel/get_consumeradmin
       {
         try {
           int id = AdminIDHelper.read (in);
           ConsumerAdmin $result = null;
           $result = this.get_consumeradmin (id);
           out = $rh.createReply();
           ConsumerAdminHelper.write (out, $result);
         } catch (AdminNotFound $ex) {
           out = $rh.createExceptionReply ();
           AdminNotFoundHelper.write (out, $ex);
         }
         break;
       }

       case 7:  // org.omg.CosNotifyChannelAdmin/EventChannel/get_supplieradmin
       {
         try {
           int id = AdminIDHelper.read (in);
           SupplierAdmin $result = null;
           $result = this.get_supplieradmin (id);
           out = $rh.createReply();
           SupplierAdminHelper.write (out, $result);
         } catch (AdminNotFound $ex) {
           out = $rh.createExceptionReply ();
           AdminNotFoundHelper.write (out, $ex);
         }
         break;
       }

       case 8:  // org.omg.CosNotifyChannelAdmin/EventChannel/get_all_consumeradmins
       {
         int $result[] = null;
         $result = this.get_all_consumeradmins ();
         out = $rh.createReply();
         AdminIDSeqHelper.write (out, $result);
         break;
       }

       case 9:  // org.omg.CosNotifyChannelAdmin/EventChannel/get_all_supplieradmins
       {
         int $result[] = null;
         $result = this.get_all_supplieradmins ();
         out = $rh.createReply();
         AdminIDSeqHelper.write (out, $result);
         break;
       }

       case 10:  // org.omg.CosNotification/QoSAdmin/get_qos
       {
         org.omg.CosNotification.Property $result[] = null;
         $result = this.get_qos ();
         out = $rh.createReply();
         org.omg.CosNotification.PropertySeqHelper.write (out, $result);
         break;
       }

       case 11:  // org.omg.CosNotification/QoSAdmin/set_qos
       {
         try {
           org.omg.CosNotification.Property qos[] = org.omg.CosNotification.QoSPropertiesHelper.read (in);
           this.set_qos (qos);
           out = $rh.createReply();
         } catch (org.omg.CosNotification.UnsupportedQoS $ex) {
           out = $rh.createExceptionReply ();
           org.omg.CosNotification.UnsupportedQoSHelper.write (out, $ex);
         }
         break;
       }

       case 12:  // org.omg.CosNotification/QoSAdmin/validate_qos
       {
         try {
           org.omg.CosNotification.Property required_qos[] = org.omg.CosNotification.QoSPropertiesHelper.read (in);
           org.omg.CosNotification.NamedPropertyRangeSeqHolder available_qos = new org.omg.CosNotification.NamedPropertyRangeSeqHolder ();
           this.validate_qos (required_qos, available_qos);
           out = $rh.createReply();
           org.omg.CosNotification.NamedPropertyRangeSeqHelper.write (out, available_qos.value);
         } catch (org.omg.CosNotification.UnsupportedQoS $ex) {
           out = $rh.createExceptionReply ();
           org.omg.CosNotification.UnsupportedQoSHelper.write (out, $ex);
         }
         break;
       }

       case 13:  // org.omg.CosNotification/AdminPropertiesAdmin/get_admin
       {
         org.omg.CosNotification.Property $result[] = null;
         $result = this.get_admin ();
         out = $rh.createReply();
         org.omg.CosNotification.PropertySeqHelper.write (out, $result);
         break;
       }

       case 14:  // org.omg.CosNotification/AdminPropertiesAdmin/set_admin
       {
         try {
           org.omg.CosNotification.Property admin[] = org.omg.CosNotification.AdminPropertiesHelper.read (in);
           this.set_admin (admin);
           out = $rh.createReply();
         } catch (org.omg.CosNotification.UnsupportedAdmin $ex) {
           out = $rh.createExceptionReply ();
           org.omg.CosNotification.UnsupportedAdminHelper.write (out, $ex);
         }
         break;
       }

       case 15:  // org.omg.CosEventChannelAdmin/EventChannel/for_consumers
       {
         org.omg.CosEventChannelAdmin.ConsumerAdmin $result = null;
         $result = this.for_consumers ();
         out = $rh.createReply();
         org.omg.CosEventChannelAdmin.ConsumerAdminHelper.write (out, $result);
         break;
       }

       case 16:  // org.omg.CosEventChannelAdmin/EventChannel/for_suppliers
       {
         org.omg.CosEventChannelAdmin.SupplierAdmin $result = null;
         $result = this.for_suppliers ();
         out = $rh.createReply();
         org.omg.CosEventChannelAdmin.SupplierAdminHelper.write (out, $result);
         break;
       }

       case 17:  // org.omg.CosEventChannelAdmin/EventChannel/destroy
       {
         this.destroy ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:omg.org/CosNotifyChannelAdmin/EventChannel:1.0",
    "IDL:omg.org/CosNotification/QoSAdmin:1.0",
    "IDL:omg.org/CosNotification/AdminPropertiesAdmin:1.0",
    "IDL:omg.org/CosEventChannelAdmin/EventChannel:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public EventChannel _this() 
  {
    return EventChannelHelper.narrow(
    super._this_object());
  }

  public EventChannel _this(org.omg.CORBA.ORB orb) 
  {
    return EventChannelHelper.narrow(
    super._this_object(orb));
  }


} // class EventChannelPOA
