package org.omg.CosNotifyChannelAdmin;

/**
* org.omg.CosNotifyChannelAdmin/ObtainInfoModeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CosNotifyChannelAdmin.idl
* jueves 5 de septiembre de 2019 02:16:14 AM CDT
*/

public final class ObtainInfoModeHolder implements org.omg.CORBA.portable.Streamable
{
  public ObtainInfoMode value = null;

  public ObtainInfoModeHolder ()
  {
  }

  public ObtainInfoModeHolder (ObtainInfoMode initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ObtainInfoModeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ObtainInfoModeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ObtainInfoModeHelper.type ();
  }

}
