package org.omg.CosNotifyChannelAdmin;


/**
* org.omg.CosNotifyChannelAdmin/ProxyNotFound.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CosNotifyChannelAdmin.idl
* jueves 5 de septiembre de 2019 02:16:17 AM CDT
*/

public final class ProxyNotFound extends org.omg.CORBA.UserException
{

  public ProxyNotFound ()
  {
    super(ProxyNotFoundHelper.id());
  } // ctor


  public ProxyNotFound (String $reason)
  {
    super(ProxyNotFoundHelper.id() + "  " + $reason);
  } // ctor

} // class ProxyNotFound
