package org.omg.CosNotifyChannelAdmin;


/**
* org.omg.CosNotifyChannelAdmin/SequenceProxyPullSupplier.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CosNotifyChannelAdmin.idl
* jueves 5 de septiembre de 2019 02:16:15 AM CDT
*/


// StructuredProxyPullSupplier
public interface SequenceProxyPullSupplier extends SequenceProxyPullSupplierOperations, ProxySupplier, org.omg.CosNotifyComm.SequencePullSupplier
{
} // interface SequenceProxyPullSupplier
