package org.omg.CosNotifyChannelAdmin;


/**
* org.omg.CosNotifyChannelAdmin/SequenceProxyPullConsumer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CosNotifyChannelAdmin.idl
* jueves 5 de septiembre de 2019 02:16:16 AM CDT
*/


// StructuredProxyPullConsumer
public interface SequenceProxyPullConsumer extends SequenceProxyPullConsumerOperations, ProxyConsumer, org.omg.CosNotifyComm.SequencePullConsumer
{
} // interface SequenceProxyPullConsumer
