package org.omg.CosNotifyChannelAdmin;


/**
* org.omg.CosNotifyChannelAdmin/SequenceProxyPullConsumerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CosNotifyChannelAdmin.idl
* jueves 5 de septiembre de 2019 02:16:16 AM CDT
*/


// StructuredProxyPullConsumer
public interface SequenceProxyPullConsumerOperations  extends ProxyConsumerOperations, org.omg.CosNotifyComm.SequencePullConsumerOperations
{
  void connect_sequence_pull_supplier(org.omg.CosNotifyComm.SequencePullSupplier pull_supplier) throws org.omg.CosEventChannelAdmin.AlreadyConnected, org.omg.CosEventChannelAdmin.TypeError;
  void suspend_connection() throws ConnectionAlreadyInactive, NotConnected;
  void resume_connection() throws ConnectionAlreadyActive, NotConnected;
} // interface SequenceProxyPullConsumerOperations
