package org.omg.CosNotifyChannelAdmin;

/**
* org.omg.CosNotifyChannelAdmin/SequenceProxyPushSupplierHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CosNotifyChannelAdmin.idl
* jueves 5 de septiembre de 2019 02:16:16 AM CDT
*/


// StructuredProxyPushSupplier
public final class SequenceProxyPushSupplierHolder implements org.omg.CORBA.portable.Streamable
{
  public SequenceProxyPushSupplier value = null;

  public SequenceProxyPushSupplierHolder ()
  {
  }

  public SequenceProxyPushSupplierHolder (SequenceProxyPushSupplier initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SequenceProxyPushSupplierHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SequenceProxyPushSupplierHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SequenceProxyPushSupplierHelper.type ();
  }

}
