package org.omg.CosNotifyChannelAdmin;


/**
* org.omg.CosNotifyChannelAdmin/StructuredProxyPullConsumer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CosNotifyChannelAdmin.idl
* jueves 5 de septiembre de 2019 02:16:16 AM CDT
*/


// ProxyPullConsumer
public interface StructuredProxyPullConsumer extends StructuredProxyPullConsumerOperations, ProxyConsumer, org.omg.CosNotifyComm.StructuredPullConsumer
{
} // interface StructuredProxyPullConsumer
