package org.omg.CosNotifyChannelAdmin;


/**
* org.omg.CosNotifyChannelAdmin/StructuredProxyPullSupplierOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CosNotifyChannelAdmin.idl
* jueves 5 de septiembre de 2019 02:16:15 AM CDT
*/


// ProxyPullSupplier
public interface StructuredProxyPullSupplierOperations  extends ProxySupplierOperations, org.omg.CosNotifyComm.StructuredPullSupplierOperations
{
  void connect_structured_pull_consumer(org.omg.CosNotifyComm.StructuredPullConsumer pull_consumer) throws org.omg.CosEventChannelAdmin.AlreadyConnected;
} // interface StructuredProxyPullSupplierOperations
