package org.omg.CosNotifyChannelAdmin;


/**
* org.omg.CosNotifyChannelAdmin/StructuredProxyPullConsumerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CosNotifyChannelAdmin.idl
* jueves 5 de septiembre de 2019 02:16:16 AM CDT
*/


// ProxyPullConsumer
public interface StructuredProxyPullConsumerOperations  extends ProxyConsumerOperations, org.omg.CosNotifyComm.StructuredPullConsumerOperations
{
  void connect_structured_pull_supplier(org.omg.CosNotifyComm.StructuredPullSupplier pull_supplier) throws org.omg.CosEventChannelAdmin.AlreadyConnected, org.omg.CosEventChannelAdmin.TypeError;
  void suspend_connection() throws ConnectionAlreadyInactive, NotConnected;
  void resume_connection() throws ConnectionAlreadyActive, NotConnected;
} // interface StructuredProxyPullConsumerOperations
