package org.omg.CosNotifyChannelAdmin;


/**
* org.omg.CosNotifyChannelAdmin/SupplierAdmin.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CosNotifyChannelAdmin.idl
* jueves 5 de septiembre de 2019 02:16:17 AM CDT
*/


// ConsumerAdmin
public interface SupplierAdmin extends SupplierAdminOperations, org.omg.CosNotification.QoSAdmin, org.omg.CosNotifyComm.NotifyPublish, org.omg.CosNotifyFilter.FilterAdmin, org.omg.CosEventChannelAdmin.SupplierAdmin
{
} // interface SupplierAdmin
