package org.omg.CSIRPConstDefs;


/**
* org.omg.CSIRPConstDefs/ResultType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CSIRPConstDefs.idl
* jueves 5 de septiembre de 2019 02:16:49 AM CDT
*/


/*
  It specifies whether the operation is success or failed.
  */
public class ResultType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static ResultType[] __array = new ResultType [__size];

  public static final int _Success = 0;
  public static final ResultType Success = new ResultType(_Success);
  public static final int _Failure = 1;
  public static final ResultType Failure = new ResultType(_Failure);

  public int value ()
  {
    return __value;
  }

  public static ResultType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected ResultType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class ResultType
