package org.omg.CSIRPConstDefs;


/**
* org.omg.CSIRPConstDefs/ResultTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CSIRPConstDefs.idl
* jueves 5 de septiembre de 2019 02:16:49 AM CDT
*/


/*
  It specifies whether the operation is success or failed.
  */
abstract public class ResultTypeHelper
{
  private static String  _id = "IDL:3gppsa5.org/CSIRPConstDefs/ResultType:1.0";

  public static void insert (org.omg.CORBA.Any a, ResultType that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ResultType extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (ResultTypeHelper.id (), "ResultType", new String[] { "Success", "Failure"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ResultType read (org.omg.CORBA.portable.InputStream istream)
  {
    return ResultType.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ResultType value)
  {
    ostream.write_long (value.value ());
  }

}
