package org.omg.CosNotification;

/**
* org.omg.CosNotification/_EventTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CosNotification.idl
* jueves 5 de septiembre de 2019 01:57:52 AM CDT
*/

public final class _EventTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public _EventType value = null;

  public _EventTypeHolder ()
  {
  }

  public _EventTypeHolder (_EventType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = _EventTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    _EventTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return _EventTypeHelper.type ();
  }

}
