package org.omg.CosNotification;


/**
* org.omg.CosNotification/AdminPropertiesAdminOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CosNotification.idl
* jueves 5 de septiembre de 2019 01:57:53 AM CDT
*/


// RejectNewEvents takes on a value of type Boolean
public interface AdminPropertiesAdminOperations 
{
  Property[] get_admin();
  void set_admin(Property[] admin) throws UnsupportedAdmin;
} // interface AdminPropertiesAdminOperations
