package org.omg.CosNotification;


/**
* org.omg.CosNotification/EventBatchHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CosNotification.idl
* jueves 5 de septiembre de 2019 01:57:53 AM CDT
*/


// StructuredEvent
abstract public class EventBatchHelper
{
  private static String  _id = "IDL:omg.org/CosNotification/EventBatch:1.0";

  public static void insert (org.omg.CORBA.Any a, StructuredEvent[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static StructuredEvent[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = StructuredEventHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (EventBatchHelper.id (), "EventBatch", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static StructuredEvent[] read (org.omg.CORBA.portable.InputStream istream)
  {
    StructuredEvent value[] = null;
    int _len0 = istream.read_long ();
    value = new StructuredEvent[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = StructuredEventHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, StructuredEvent[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      StructuredEventHelper.write (ostream, value[_i0]);
  }

}
