package org.omg.CosNotification;


/**
* org.omg.CosNotification/EventHeader.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CosNotification.idl
* jueves 5 de septiembre de 2019 01:57:52 AM CDT
*/

public final class EventHeader implements org.omg.CORBA.portable.IDLEntity
{
  public FixedEventHeader fixed_header = null;
  public Property variable_header[] = null;

  public EventHeader ()
  {
  } // ctor

  public EventHeader (FixedEventHeader _fixed_header, Property[] _variable_header)
  {
    fixed_header = _fixed_header;
    variable_header = _variable_header;
  } // ctor

} // class EventHeader
