package org.omg.CosNotification;


/**
* org.omg.CosNotification/HighestPriority.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CosNotification.idl
* jueves 5 de septiembre de 2019 01:57:53 AM CDT
*/

public interface HighestPriority
{
  public static final short value = (short)(32767);
}
