package org.omg.CosNotification;


/**
* org.omg.CosNotification/OptionalHeaderFieldsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CosNotification.idl
* jueves 5 de septiembre de 2019 01:57:52 AM CDT
*/


// The following are the same, but serve different purposes.
abstract public class OptionalHeaderFieldsHelper
{
  private static String  _id = "IDL:omg.org/CosNotification/OptionalHeaderFields:1.0";

  public static void insert (org.omg.CORBA.Any a, Property[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Property[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = PropertyHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (PropertySeqHelper.id (), "PropertySeq", __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (OptionalHeaderFieldsHelper.id (), "OptionalHeaderFields", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Property[] read (org.omg.CORBA.portable.InputStream istream)
  {
    Property value[] = null;
    value = PropertySeqHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Property[] value)
  {
    PropertySeqHelper.write (ostream, value);
  }

}
