package org.omg.CosNotification;


/**
* org.omg.CosNotification/PropertyError.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CosNotification.idl
* jueves 5 de septiembre de 2019 01:57:52 AM CDT
*/

public final class PropertyError implements org.omg.CORBA.portable.IDLEntity
{
  public QoSError_code code = null;
  public String name = null;
  public PropertyRange available_range = null;

  public PropertyError ()
  {
  } // ctor

  public PropertyError (QoSError_code _code, String _name, PropertyRange _available_range)
  {
    code = _code;
    name = _name;
    available_range = _available_range;
  } // ctor

} // class PropertyError
