package org.omg.CosNotification;

/**
* org.omg.CosNotification/QoSAdminHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CosNotification.idl
* jueves 5 de septiembre de 2019 01:57:53 AM CDT
*/


// MaxEventsPerConsumer takes on a value of type long
public final class QoSAdminHolder implements org.omg.CORBA.portable.Streamable
{
  public QoSAdmin value = null;

  public QoSAdminHolder ()
  {
  }

  public QoSAdminHolder (QoSAdmin initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = QoSAdminHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    QoSAdminHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return QoSAdminHelper.type ();
  }

}
