package org.omg.CosNotification;


/**
* org.omg.CosNotification/QoSError_code.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CosNotification.idl
* jueves 5 de septiembre de 2019 01:57:52 AM CDT
*/

public class QoSError_code implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 7;
  private static QoSError_code[] __array = new QoSError_code [__size];

  public static final int _UNSUPPORTED_PROPERTY = 0;
  public static final QoSError_code UNSUPPORTED_PROPERTY = new QoSError_code(_UNSUPPORTED_PROPERTY);
  public static final int _UNAVAILABLE_PROPERTY = 1;
  public static final QoSError_code UNAVAILABLE_PROPERTY = new QoSError_code(_UNAVAILABLE_PROPERTY);
  public static final int _UNSUPPORTED_VALUE = 2;
  public static final QoSError_code UNSUPPORTED_VALUE = new QoSError_code(_UNSUPPORTED_VALUE);
  public static final int _UNAVAILABLE_VALUE = 3;
  public static final QoSError_code UNAVAILABLE_VALUE = new QoSError_code(_UNAVAILABLE_VALUE);
  public static final int _BAD_PROPERTY = 4;
  public static final QoSError_code BAD_PROPERTY = new QoSError_code(_BAD_PROPERTY);
  public static final int _BAD_TYPE = 5;
  public static final QoSError_code BAD_TYPE = new QoSError_code(_BAD_TYPE);
  public static final int _BAD_VALUE = 6;
  public static final QoSError_code BAD_VALUE = new QoSError_code(_BAD_VALUE);

  public int value ()
  {
    return __value;
  }

  public static QoSError_code from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected QoSError_code (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class QoSError_code
