package org.omg.KernelCmNotifications;


/**
* org.omg.KernelCmNotifications/AttributeValueChangeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.KernelCmNotifications.idl
* jueves 5 de septiembre de 2019 02:20:05 AM CDT
*/


/**
       *  Constant definitions for the Attribute Value Change
       *  notification
       */
public interface AttributeValueChangeOperations  extends NotificationCommonOperations
{
} // interface AttributeValueChangeOperations
