package org.omg.KernelCmNotifications;

/**
* org.omg.KernelCmNotifications/AttributeValueChangeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.KernelCmNotifications.idl
* jueves 5 de septiembre de 2019 02:20:05 AM CDT
*/


/**
       *  Constant definitions for the Attribute Value Change
       *  notification
       */
public final class AttributeValueChangeHolder implements org.omg.CORBA.portable.Streamable
{
  public AttributeValueChange value = null;

  public AttributeValueChangeHolder ()
  {
  }

  public AttributeValueChangeHolder (AttributeValueChange initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AttributeValueChangeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AttributeValueChangeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AttributeValueChangeHelper.type ();
  }

}
