package org.omg.KernelCmNotifications;


/**
* org.omg.KernelCmNotifications/CMSynchronizationRecommended.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.KernelCmNotifications.idl
* jueves 5 de septiembre de 2019 02:20:05 AM CDT
*/


/**
       *  Constant definitions for the CM Synchronization Recommended notification
       */
public interface CMSynchronizationRecommended extends CMSynchronizationRecommendedOperations, org.omg.NotificationIRPNotifications.Notify, org.omg.CORBA.portable.IDLEntity
{
  public static final String EVENT_TYPE = "x9";

  /**
          *  This constant defines the name of the  
          *  additional text property. 
          *  The data type for the value of this property
          *  is a string.
          */
  public static final String ADDITIONAL_TEXT = org.omg.KernelCmConstDefs.AttributeNameValue.ADDITIONAL_TEXT;

  /**
          *  This constant defines the name of the  
          *  base MO class property. 
          *  The value part of this property will carry
          *  the base MO class name as a string.
          */
  public static final String BASE_MO_CLASS = org.omg.KernelCmConstDefs.AttributeNameValue.BASE_MO_CLASS;

  /**
          *  This constant defines the name of the  
          *  base MO instance property. 
          *  The value part of this property will carry
          *  the base MO distinguished name as a string.
          */
  public static final String BASE_MO_INSTANCE = org.omg.KernelCmConstDefs.AttributeNameValue.BASE_MO_INSTANCE;

  /**
          *  This constant defines the name of the  
          *  scope property. 
          *  The data type for the value of this property
          *  is org.omg.KernelCmConstDefs::ScopePara.
          */
  public static final String SCOPE = org.omg.KernelCmConstDefs.AttributeNameValue.SCOPE;
} // interface CMSynchronizationRecommended
