package org.omg.KernelCmNotifications;


/**
* org.omg.KernelCmNotifications/NotificationCommon.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.KernelCmNotifications.idl
* jueves 5 de septiembre de 2019 02:20:05 AM CDT
*/


/**
       *  This interface defines fields that are common for all 
       *  notification types. 
       *  All constants in the scope of this interface will be 
       *  visible in the interfaces that inherits this. 
       *  For instance constant 
       *  NotificationCommon::MANAGED_OBJECT_CLASS
       *  can be addressed by MODeletion::MANAGED_OBJECT_CLASS
       */
public interface NotificationCommon extends NotificationCommonOperations, org.omg.NotificationIRPNotifications.Notify, org.omg.CORBA.portable.IDLEntity
{

  /**
          *  This constant defines the name of the  
          *  source indicator  property.
          */
  public static final String SOURCE_INDICATOR = org.omg.KernelCmConstDefs.AttributeNameValue.SOURCE_INDICATOR;

  /**
          * Valid values for the SOURCE_INDICATOR 
          * property
          */
  public static final String RESOURCE_OPERATION = "RESOURCE OPERATION";
  public static final String MANAGEMENT_OPERATION = "MANAGEMENT OPERATION";
  public static final String UNKNOWN_OPERATION = "UNKNOWN";

  /**
          *  This constant defines the name of the  
          *  additional text property. 
          *  The data type for the value of this property
          *  is a string.
          */
  public static final String ADDITIONAL_TEXT = org.omg.KernelCmConstDefs.AttributeNameValue.ADDITIONAL_TEXT;

  /**
          *  This constant defines the name of the  
          *  correlated notifications property. 
          *  The value part of the property is 
          *    org.omg.KernelCmConstDefs::CorrelatedNotificationSetType
          */
  public static final String CORRELATED_NOTIFICATIONS = org.omg.KernelCmConstDefs.AttributeNameValue.CORRELATED_NOTIFICATIONS;
} // interface NotificationCommon
