package org.omg.KernelCmNotifications;


/**
* org.omg.KernelCmNotifications/StateChange.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.KernelCmNotifications.idl
* jueves 5 de septiembre de 2019 02:20:05 AM CDT
*/


/**
       *  Constant definitions for the State Change notification
       */
public interface StateChange extends StateChangeOperations, NotificationCommon, org.omg.CORBA.portable.IDLEntity
{
  public static final String EVENT_TYPE = "xA";
} // interface StateChange
