package org.omg.NotificationIRPSystem;

/**
* org.omg.NotificationIRPSystem/AlreadySubscribedHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.NotificationIRPSystem.idl
* jueves 5 de septiembre de 2019 01:39:37 AM CDT
*/

public final class AlreadySubscribedHolder implements org.omg.CORBA.portable.Streamable
{
  public AlreadySubscribed value = null;

  public AlreadySubscribedHolder ()
  {
  }

  public AlreadySubscribedHolder (AlreadySubscribed initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AlreadySubscribedHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AlreadySubscribedHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AlreadySubscribedHelper.type ();
  }

}
