package org.omg.NotificationIRPSystem;

/**
* org.omg.NotificationIRPSystem/AtLeastOneNotificationCategoryNotSupportedHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.NotificationIRPSystem.idl
* jueves 5 de septiembre de 2019 01:39:37 AM CDT
*/

public final class AtLeastOneNotificationCategoryNotSupportedHolder implements org.omg.CORBA.portable.Streamable
{
  public AtLeastOneNotificationCategoryNotSupported value = null;

  public AtLeastOneNotificationCategoryNotSupportedHolder ()
  {
  }

  public AtLeastOneNotificationCategoryNotSupportedHolder (AtLeastOneNotificationCategoryNotSupported initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AtLeastOneNotificationCategoryNotSupportedHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AtLeastOneNotificationCategoryNotSupportedHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AtLeastOneNotificationCategoryNotSupportedHelper.type ();
  }

}
