package org.omg.NotificationIRPSystem;


/**
* org.omg.NotificationIRPSystem/Attach.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.NotificationIRPSystem.idl
* jueves 5 de septiembre de 2019 01:39:37 AM CDT
*/

public final class Attach extends org.omg.CORBA.UserException
{
  public String reason = null;

  public Attach ()
  {
    super(AttachHelper.id());
  } // ctor

  public Attach (String _reason)
  {
    super(AttachHelper.id());
    reason = _reason;
  } // ctor


  public Attach (String $reason, String _reason)
  {
    super(AttachHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class Attach
