package org.omg.NotificationIRPSystem;


/**
* org.omg.NotificationIRPSystem/GetNotificationCategories.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.NotificationIRPSystem.idl
* jueves 5 de septiembre de 2019 01:39:37 AM CDT
*/

public final class GetNotificationCategories extends org.omg.CORBA.UserException
{
  public String reason = null;

  public GetNotificationCategories ()
  {
    super(GetNotificationCategoriesHelper.id());
  } // ctor

  public GetNotificationCategories (String _reason)
  {
    super(GetNotificationCategoriesHelper.id());
    reason = _reason;
  } // ctor


  public GetNotificationCategories (String $reason, String _reason)
  {
    super(GetNotificationCategoriesHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class GetNotificationCategories
