package org.omg.NotificationIRPSystem;


/**
* org.omg.NotificationIRPSystem/NotificationIRPHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.NotificationIRPSystem.idl
* jueves 5 de septiembre de 2019 01:39:38 AM CDT
*/

abstract public class NotificationIRPHelper
{
  private static String  _id = "IDL:3gppsa5.org/NotificationIRPSystem/NotificationIRP:1.0";

  public static void insert (org.omg.CORBA.Any a, NotificationIRP that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static NotificationIRP extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (NotificationIRPHelper.id (), "NotificationIRP");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static NotificationIRP read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_NotificationIRPStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, NotificationIRP value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static NotificationIRP narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof NotificationIRP){
      return (NotificationIRP)obj;
    }
    else if (!obj._is_a (id ())){
      System.out.println(obj);
      throw new org.omg.CORBA.BAD_PARAM ();
    }
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _NotificationIRPStub stub = new _NotificationIRPStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static NotificationIRP unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof NotificationIRP)
      return (NotificationIRP)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _NotificationIRPStub stub = new _NotificationIRPStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
