package org.omg.NotificationIRPSystem;


/**
* org.omg.NotificationIRPSystem/NotificationIRP.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.NotificationIRPSystem.idl
* jueves 5 de septiembre de 2019 01:39:38 AM CDT
*/

public interface NotificationIRP extends NotificationIRPOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface NotificationIRP
