package org.omg.BasicCMIRPConstDefs;


/**
* org.omg.BasicCMIRPConstDefs/AttributeErrorSeqHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.BasicCMIRPConstDefs.idl
* jueves 5 de septiembre de 2019 02:15:01 AM CDT
*/

abstract public class AttributeErrorSeqHelper
{
  private static String  _id = "IDL:3gppsa5.org/BasicCMIRPConstDefs/AttributeErrorSeq:1.0";

  public static void insert (org.omg.CORBA.Any a, AttributeError[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static AttributeError[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = AttributeErrorHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (AttributeErrorSeqHelper.id (), "AttributeErrorSeq", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static AttributeError[] read (org.omg.CORBA.portable.InputStream istream)
  {
    AttributeError value[] = null;
    int _len0 = istream.read_long ();
    value = new AttributeError[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = AttributeErrorHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, AttributeError[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      AttributeErrorHelper.write (ostream, value[_i0]);
  }

}
