package org.omg.BasicCMIRPConstDefs;

/**
* org.omg.BasicCMIRPConstDefs/ModifyAttributeErrorsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.BasicCMIRPConstDefs.idl
* jueves 5 de septiembre de 2019 02:15:01 AM CDT
*/

public final class ModifyAttributeErrorsHolder implements org.omg.CORBA.portable.Streamable
{
  public ModifyAttributeErrors value = null;

  public ModifyAttributeErrorsHolder ()
  {
  }

  public ModifyAttributeErrorsHolder (ModifyAttributeErrors initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ModifyAttributeErrorsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ModifyAttributeErrorsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ModifyAttributeErrorsHelper.type ();
  }

}
