package org.omg.BasicCMIRPConstDefs;


/**
* org.omg.BasicCMIRPConstDefs/ModifyAttributeErrorsSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.BasicCMIRPConstDefs.idl
* jueves 5 de septiembre de 2019 02:15:01 AM CDT
*/

public final class ModifyAttributeErrorsSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public ModifyAttributeErrors value[] = null;

  public ModifyAttributeErrorsSeqHolder ()
  {
  }

  public ModifyAttributeErrorsSeqHolder (ModifyAttributeErrors[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ModifyAttributeErrorsSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ModifyAttributeErrorsSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ModifyAttributeErrorsSeqHelper.type ();
  }

}
