package org.omg.BasicCMIRPConstDefs;


/**
* org.omg.BasicCMIRPConstDefs/ResultHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.BasicCMIRPConstDefs.idl
* jueves 5 de septiembre de 2019 02:15:01 AM CDT
*/

abstract public class ResultHelper
{
  private static String  _id = "IDL:3gppsa5.org/BasicCMIRPConstDefs/Result:1.0";

  public static void insert (org.omg.CORBA.Any a, Result that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Result extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (DNHelper.id (), "DN", _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "mo",
            _tcOf_members0,
            null);
          _tcOf_members0 = MOAttributeHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (MOAttributeSetHelper.id (), "MOAttributeSet", _tcOf_members0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "attributes",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (ResultHelper.id (), "Result", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Result read (org.omg.CORBA.portable.InputStream istream)
  {
    Result value = new Result ();
    value.mo = istream.read_string ();
    value.attributes = MOAttributeSetHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Result value)
  {
    ostream.write_string (value.mo);
    MOAttributeSetHelper.write (ostream, value.attributes);
  }

}
