package org.omg.GenericNetworkResourcesNRMDefs.LinkAttributeTypes;


/**
* org.omg.GenericNetworkResourcesNRMDefs/LinkAttributeTypes/LinkTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.GenericNetworkResourcesNRMDefs.idl
* jueves 5 de septiembre de 2019 02:19:12 AM CDT
*/

abstract public class LinkTypeHelper
{
  private static String  _id = "IDL:3gppsa5.org/GenericNetworkResourcesNRMDefs/LinkAttributeTypes/LinkType:1.0";

  public static void insert (org.omg.CORBA.Any a, LinkType that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static LinkType extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (LinkTypeHelper.id (), "LinkType", new String[] { "Signalling", "Bearer", "OAM_AND_P", "Other"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static LinkType read (org.omg.CORBA.portable.InputStream istream)
  {
    return LinkType.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, LinkType value)
  {
    ostream.write_long (value.value ());
  }

}
