package org.omg.GenericNetworkResourcesNRMDefs.LinkAttributeTypes;


/**
* org.omg.GenericNetworkResourcesNRMDefs/LinkAttributeTypes/LinkType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.GenericNetworkResourcesNRMDefs.idl
* jueves 5 de septiembre de 2019 02:19:12 AM CDT
*/

public class LinkType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 4;
  private static LinkType[] __array = new LinkType [__size];

  public static final int _Signalling = 0;
  public static final LinkType Signalling = new LinkType(_Signalling);
  public static final int _Bearer = 1;
  public static final LinkType Bearer = new LinkType(_Bearer);
  public static final int _OAM_AND_P = 2;
  public static final LinkType OAM_AND_P = new LinkType(_OAM_AND_P);
  public static final int _Other = 3;
  public static final LinkType Other = new LinkType(_Other);

  public int value ()
  {
    return __value;
  }

  public static LinkType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected LinkType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class LinkType
