package org.omg.GenericNetworkResourcesNRMDefs.LinkAttributeTypes;


/**
* org.omg.GenericNetworkResourcesNRMDefs/LinkAttributeTypes/LinkTypeTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.GenericNetworkResourcesNRMDefs.idl
* jueves 5 de septiembre de 2019 02:19:12 AM CDT
*/

public final class LinkTypeTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public LinkType value[] = null;

  public LinkTypeTypeHolder ()
  {
  }

  public LinkTypeTypeHolder (LinkType[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LinkTypeTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LinkTypeTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LinkTypeTypeHelper.type ();
  }

}
