package org.omg.FileTransferIRPConstDefs;


/**
* org.omg.FileTransferIRPConstDefs/AttributeNameValue.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.FileTransferIRPConstDefs.idl
* jueves 5 de septiembre de 2019 02:17:32 AM CDT
*/


/*
   Define the parameters specified in the notifyFileReady
   and notifyFilePreparationError notifications.
   */
public interface AttributeNameValue extends AttributeNameValueOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
  public static final String FILE_INFO_LIST = "FILE_INFO_LIST";
  public static final String ADDITIONAL_TEXT = "ADDITIONAL_TEXT";
  public static final String REASON = "REASON";
} // interface AttributeNameValue
