package org.omg.FileTransferIRPConstDefs;


/**
* org.omg.FileTransferIRPConstDefs/CT_MANAGEMENT_DATA_TYPE.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.FileTransferIRPConstDefs.idl
* jueves 5 de septiembre de 2019 02:17:31 AM CDT
*/

public interface CT_MANAGEMENT_DATA_TYPE
{

  //Test Management
  public static final short value = (short)(5);
}
