package org.omg.FileTransferIRPConstDefs;


/**
* org.omg.FileTransferIRPConstDefs/URL.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.FileTransferIRPConstDefs.idl
* jueves 5 de septiembre de 2019 02:17:31 AM CDT
*/

public final class URL implements org.omg.CORBA.portable.IDLEntity
{
  private String ___file_location_url;
  private short ___nouse;
  private boolean __discriminator;
  private boolean __uninitialized = true;

  public URL ()
  {
  }

  public boolean discriminator ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    return __discriminator;
  }

  public String file_location_url ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifyfile_location_url (__discriminator);
    return ___file_location_url;
  }

  public void file_location_url (String value)
  {
    __discriminator = true;
    ___file_location_url = value;
    __uninitialized = false;
  }

  public void file_location_url (boolean discriminator, String value)
  {
    verifyfile_location_url (discriminator);
    __discriminator = discriminator;
    ___file_location_url = value;
    __uninitialized = false;
  }

  private void verifyfile_location_url (boolean discriminator)
  {
    if (discriminator != true)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public short nouse ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifynouse (__discriminator);
    return ___nouse;
  }

  public void nouse (short value)
  {
    __discriminator = false;
    ___nouse = value;
    __uninitialized = false;
  }

  public void nouse (boolean discriminator, short value)
  {
    verifynouse (discriminator);
    __discriminator = discriminator;
    ___nouse = value;
    __uninitialized = false;
  }

  private void verifynouse (boolean discriminator)
  {
    if (discriminator != false)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

} // class URL
