package org.omg.FileTransferIRPConstDefs;

/**
* org.omg.FileTransferIRPConstDefs/URLHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.FileTransferIRPConstDefs.idl
* jueves 5 de septiembre de 2019 02:17:31 AM CDT
*/

public final class URLHolder implements org.omg.CORBA.portable.Streamable
{
  public URL value = null;

  public URLHolder ()
  {
  }

  public URLHolder (URL initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = URLHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    URLHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return URLHelper.type ();
  }

}
