package org.omg.CosNotifyComm;


/**
* org.omg.CosNotifyComm/PullConsumerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CosNotifyComm.idl
* jueves 5 de septiembre de 2019 02:16:24 AM CDT
*/


// PushConsumer
public interface PullConsumerOperations  extends NotifyPublishOperations, org.omg.CosEventComm.PullConsumerOperations
{
} // interface PullConsumerOperations
