package org.omg.CosNotifyComm;


/**
* org.omg.CosNotifyComm/PushConsumer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CosNotifyComm.idl
* jueves 5 de septiembre de 2019 02:16:24 AM CDT
*/


// NotifySubscribe
public interface PushConsumer extends PushConsumerOperations, NotifyPublish, org.omg.CosEventComm.PushConsumer
{
} // interface PushConsumer
