package org.omg.CosNotifyComm;


/**
* org.omg.CosNotifyComm/SequencePushConsumer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CosNotifyComm.idl
* jueves 5 de septiembre de 2019 02:16:25 AM CDT
*/


// StructuredPushSupplier
public interface SequencePushConsumer extends SequencePushConsumerOperations, NotifyPublish, org.omg.CORBA.portable.IDLEntity
{
} // interface SequencePushConsumer
