package org.omg.CosNotifyComm;


/**
* org.omg.CosNotifyComm/SequencePushConsumerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CosNotifyComm.idl
* jueves 5 de septiembre de 2019 02:16:25 AM CDT
*/


// StructuredPushSupplier
abstract public class SequencePushConsumerHelper
{
  private static String  _id = "IDL:omg.org/CosNotifyComm/SequencePushConsumer:1.0";

  public static void insert (org.omg.CORBA.Any a, SequencePushConsumer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static SequencePushConsumer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (SequencePushConsumerHelper.id (), "SequencePushConsumer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static SequencePushConsumer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_SequencePushConsumerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, SequencePushConsumer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static SequencePushConsumer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof SequencePushConsumer)
      return (SequencePushConsumer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _SequencePushConsumerStub stub = new _SequencePushConsumerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static SequencePushConsumer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof SequencePushConsumer)
      return (SequencePushConsumer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _SequencePushConsumerStub stub = new _SequencePushConsumerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
