package org.omg.CosNotifyComm;

/**
* org.omg.CosNotifyComm/StructuredPushSupplierHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CosNotifyComm.idl
* jueves 5 de septiembre de 2019 02:16:25 AM CDT
*/


// StructuredPullSupplier
public final class StructuredPushSupplierHolder implements org.omg.CORBA.portable.Streamable
{
  public StructuredPushSupplier value = null;

  public StructuredPushSupplierHolder ()
  {
  }

  public StructuredPushSupplierHolder (StructuredPushSupplier initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StructuredPushSupplierHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StructuredPushSupplierHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StructuredPushSupplierHelper.type ();
  }

}
