package org.omg.CosNotifyComm;


/**
* org.omg.CosNotifyComm/StructuredPushSupplierOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CosNotifyComm.idl
* jueves 5 de septiembre de 2019 02:16:25 AM CDT
*/


// StructuredPullSupplier
public interface StructuredPushSupplierOperations  extends NotifySubscribeOperations
{
  void disconnect_structured_push_supplier();
} // interface StructuredPushSupplierOperations
