package org.omg.GenericIRPManagementConstDefs;


/**
* org.omg.GenericIRPManagementConstDefs/DNListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.GenericIRPManagementConstDefs.idl
* jueves 5 de septiembre de 2019 02:18:40 AM CDT
*/

public final class DNListHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public DNListHolder ()
  {
  }

  public DNListHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DNListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DNListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DNListHelper.type ();
  }

}
