package org.omg.StateManagementIRPConstDefs;


/**
* org.omg.StateManagementIRPConstDefs/AlarmStatusValues.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.StateManagementIRPConstDefs.idl
* jueves 5 de septiembre de 2019 02:21:19 AM CDT
*/


/*
   Definition of Alarm Status based on M.3100 [4], if mandatory.
   */
public class AlarmStatusValues implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 6;
  private static AlarmStatusValues[] __array = new AlarmStatusValues [__size];

  public static final int _CLEARED = 0;
  public static final AlarmStatusValues CLEARED = new AlarmStatusValues(_CLEARED);
  public static final int _INDETERMINATE = 1;
  public static final AlarmStatusValues INDETERMINATE = new AlarmStatusValues(_INDETERMINATE);
  public static final int _WARNING = 2;
  public static final AlarmStatusValues WARNING = new AlarmStatusValues(_WARNING);
  public static final int _MINOR = 3;
  public static final AlarmStatusValues MINOR = new AlarmStatusValues(_MINOR);
  public static final int _MAJOR = 4;
  public static final AlarmStatusValues MAJOR = new AlarmStatusValues(_MAJOR);
  public static final int _CRITICAL = 5;
  public static final AlarmStatusValues CRITICAL = new AlarmStatusValues(_CRITICAL);

  public int value ()
  {
    return __value;
  }

  public static AlarmStatusValues from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected AlarmStatusValues (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class AlarmStatusValues
