package org.omg.StateManagementIRPConstDefs;

/**
* org.omg.StateManagementIRPConstDefs/AvailabilityStatusValuesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.StateManagementIRPConstDefs.idl
* jueves 5 de septiembre de 2019 02:21:20 AM CDT
*/


/*
   Definition of Availability Status based on X.721 [3], if mandatory.
   */
public final class AvailabilityStatusValuesHolder implements org.omg.CORBA.portable.Streamable
{
  public AvailabilityStatusValues value = null;

  public AvailabilityStatusValuesHolder ()
  {
  }

  public AvailabilityStatusValuesHolder (AvailabilityStatusValues initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AvailabilityStatusValuesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AvailabilityStatusValuesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AvailabilityStatusValuesHelper.type ();
  }

}
