package org.omg.StateManagementIRPConstDefs;


/**
* org.omg.StateManagementIRPConstDefs/ControlStatusOldNewValueHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.StateManagementIRPOptConstDefs.idl
* jueves 5 de septiembre de 2019 02:21:33 AM CDT
*/

abstract public class ControlStatusOldNewValueHelper
{
  private static String  _id = "IDL:3gppsa5.org/org.omg.StateManagementIRPConstDefs/ControlStatusOldNewValue:1.0";

  public static void insert (org.omg.CORBA.Any a, ControlStatusOldNewValue that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ControlStatusOldNewValue extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = ControlStatusValuesHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "new",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.StateManagementIRPOptConstDefs.ControlStatusTypeOptHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "old",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (ControlStatusOldNewValueHelper.id (), "ControlStatusOldNewValue", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ControlStatusOldNewValue read (org.omg.CORBA.portable.InputStream istream)
  {
    ControlStatusOldNewValue value = new ControlStatusOldNewValue ();
    value._new = ControlStatusValuesHelper.read (istream);
    value.old = org.omg.StateManagementIRPOptConstDefs.ControlStatusTypeOptHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ControlStatusOldNewValue value)
  {
    ControlStatusValuesHelper.write (ostream, value._new);
    org.omg.StateManagementIRPOptConstDefs.ControlStatusTypeOptHelper.write (ostream, value.old);
  }

}
