package org.omg.StateManagementIRPConstDefs;

/**
* org.omg.StateManagementIRPConstDefs/ProceduralStatusValuesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.StateManagementIRPConstDefs.idl
* jueves 5 de septiembre de 2019 02:21:19 AM CDT
*/


/*
   Definition of Procedural Status based on X.721 [3], if mandatory.
   */
public final class ProceduralStatusValuesHolder implements org.omg.CORBA.portable.Streamable
{
  public ProceduralStatusValues value = null;

  public ProceduralStatusValuesHolder ()
  {
  }

  public ProceduralStatusValuesHolder (ProceduralStatusValues initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ProceduralStatusValuesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ProceduralStatusValuesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ProceduralStatusValuesHelper.type ();
  }

}
