package org.omg.StateManagementIRPConstDefs;


/**
* org.omg.StateManagementIRPConstDefs/StandbyStatusOldNewValue.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.StateManagementIRPOptConstDefs.idl
* jueves 5 de septiembre de 2019 02:21:33 AM CDT
*/

public final class StandbyStatusOldNewValue implements org.omg.CORBA.portable.IDLEntity
{
  public StandbyStatus _new = null;
  public org.omg.StateManagementIRPOptConstDefs.StandbyStatusTypeOpt old = null;

  public StandbyStatusOldNewValue ()
  {
  } // ctor

  public StandbyStatusOldNewValue (StandbyStatus __new, org.omg.StateManagementIRPOptConstDefs.StandbyStatusTypeOpt _old)
  {
    _new = __new;
    old = _old;
  } // ctor

} // class StandbyStatusOldNewValue
