package org.omg.StateManagementIRPConstDefs;

/**
* org.omg.StateManagementIRPConstDefs/UsageStateHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.StateManagementIRPConstDefs.idl
* jueves 5 de septiembre de 2019 02:21:19 AM CDT
*/


/*
   Definition of Usage State based on X.721 [3], if mandatory.
   */
public final class UsageStateHolder implements org.omg.CORBA.portable.Streamable
{
  public UsageState value = null;

  public UsageStateHolder ()
  {
  }

  public UsageStateHolder (UsageState initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = UsageStateHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    UsageStateHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return UsageStateHelper.type ();
  }

}
