package org.omg.NotificationIRPConstDefs;


/**
* org.omg.NotificationIRPConstDefs/AttributeNameValue.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.NotificationIRPConstDefs.idl
* jueves 5 de septiembre de 2019 02:10:23 AM CDT
*/


/*
   Define the parameters (in the notification header) specified in
   the Notification IRP: IS. 
   */
public interface AttributeNameValue extends AttributeNameValueOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
  public static final String NOTIFICATION_ID = "a";
  public static final String EVENT_TIME = "b";
  public static final String SYSTEM_DN = "c";
  public static final String MANAGED_OBJECT_CLASS = "d";
  public static final String MANAGED_OBJECT_INSTANCE = "e";
} // interface AttributeNameValue
