package org.omg.KernelCmConstDefs;


/**
* org.omg.KernelCmConstDefs/CorrelatedNotificationSetTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.KernelCmConstDefs.idl
* jueves 5 de septiembre de 2019 02:19:33 AM CDT
*/


/*
   Correlated Notification sets are sets of Correlated Notification
   structures.
   */
public final class CorrelatedNotificationSetTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public CorrelatedNotification value[] = null;

  public CorrelatedNotificationSetTypeHolder ()
  {
  }

  public CorrelatedNotificationSetTypeHolder (CorrelatedNotification[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CorrelatedNotificationSetTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CorrelatedNotificationSetTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CorrelatedNotificationSetTypeHelper.type ();
  }

}
