package org.omg.KernelCmConstDefs;


/**
* org.omg.KernelCmConstDefs/ScopePara.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.KernelCmConstDefs.idl
* jueves 5 de septiembre de 2019 02:19:33 AM CDT
*/

public final class ScopePara implements org.omg.CORBA.portable.IDLEntity
{
  public ScopeType type = null;
  public int level = (int)0;

  public ScopePara ()
  {
  } // ctor

  public ScopePara (ScopeType _type, int _level)
  {
    type = _type;
    level = _level;
  } // ctor

} // class ScopePara
