package org.omg.GenericIRPManagementSystem;


/**
* org.omg.GenericIRPManagementSystem/GenericIRPManagementHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.GenericIRPManagementSystem.idl
* jueves 5 de septiembre de 2019 02:18:50 AM CDT
*/

abstract public class GenericIRPManagementHelper
{
  private static String  _id = "IDL:3gppsa5.org/GenericIRPManagementSystem/GenericIRPManagement:1.0";

  public static void insert (org.omg.CORBA.Any a, GenericIRPManagement that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static GenericIRPManagement extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (GenericIRPManagementHelper.id (), "GenericIRPManagement");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static GenericIRPManagement read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GenericIRPManagementStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, GenericIRPManagement value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static GenericIRPManagement narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof GenericIRPManagement)
      return (GenericIRPManagement)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _GenericIRPManagementStub stub = new _GenericIRPManagementStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static GenericIRPManagement unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof GenericIRPManagement)
      return (GenericIRPManagement)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _GenericIRPManagementStub stub = new _GenericIRPManagementStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
