package org.omg.GenericIRPManagementSystem;


/**
* org.omg.GenericIRPManagementSystem/GenericIRPManagement.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.GenericIRPManagementSystem.idl
* jueves 5 de septiembre de 2019 02:18:50 AM CDT
*/

public interface GenericIRPManagement extends GenericIRPManagementOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GenericIRPManagement
