package org.omg.UtranNetworkResourcesNRMDefs;


/**
* org.omg.UtranNetworkResourcesNRMDefs/AntennaFunction.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.UtranNetworkResourcesNRMDefs.idl
* jueves 5 de septiembre de 2019 02:21:43 AM CDT
*/

public interface AntennaFunction extends AntennaFunctionOperations, org.omg.GenericNetworkResourcesNRMDefs.ManagedFunction, org.omg.CORBA.portable.IDLEntity
{
  public static final String CLASS = "AntennaFunction";

  //
  public static final String antennaId = "antennaFunctionId";
  public static final String retUtranCellList = "retUtranCellList";
  public static final String retTiltValue = "retTiltValue";
  public static final String compassDirection = "compassDirection";
  public static final String maxTiltValue = "maxTiltValue";
  public static final String minTiltValue = "minTiltValue";
  public static final String mechanicalOffset = "mechanicalOffset";
  public static final String retGroupName = "retGroupName";
  public static final String height = "height";
} // interface AntennaFunction
