package org.omg.UtranNetworkResourcesNRMDefs;


/**
* org.omg.UtranNetworkResourcesNRMDefs/IubLink.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.UtranNetworkResourcesNRMDefs.idl
* jueves 5 de septiembre de 2019 02:21:43 AM CDT
*/


/**
       *  Definitions for MO class IubLink
       */
public interface IubLink extends IubLinkOperations, org.omg.GenericNetworkResourcesNRMDefs.ManagedFunction, org.omg.CORBA.portable.IDLEntity
{
  public static final String CLASS = "IubLink";

  //
  public static final String iubLinkId = "iubLinkId";
  public static final String iubLinkNodeBFunction = "iubLinkNodeBFunction";
  public static final String iubLinkUtranCell = "iubLinkUtranCell";
  public static final String iubLinkATMChannelTerminationPoint = "iubLinkATMChannelTerminationPoint";
} // interface IubLink
