package org.omg.UtranNetworkResourcesNRMDefs;


/**
* org.omg.UtranNetworkResourcesNRMDefs/NodeBFunctionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.UtranNetworkResourcesNRMDefs.idl
* jueves 5 de septiembre de 2019 02:21:43 AM CDT
*/


/**
       *  Definitions for MO class NodeBFunction
       */
abstract public class NodeBFunctionHelper
{
  private static String  _id = "IDL:3gppsa5.org/org.omg.UtranNetworkResourcesNRMDefs/NodeBFunction:1.0";

  public static void insert (org.omg.CORBA.Any a, NodeBFunction that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static NodeBFunction extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (NodeBFunctionHelper.id (), "NodeBFunction");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static NodeBFunction read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_NodeBFunctionStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, NodeBFunction value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static NodeBFunction narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof NodeBFunction)
      return (NodeBFunction)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _NodeBFunctionStub stub = new _NodeBFunctionStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static NodeBFunction unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof NodeBFunction)
      return (NodeBFunction)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _NodeBFunctionStub stub = new _NodeBFunctionStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
