package org.omg.UtranNetworkResourcesNRMDefs;


/**
* org.omg.UtranNetworkResourcesNRMDefs/RncFunction.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.UtranNetworkResourcesNRMDefs.idl
* jueves 5 de septiembre de 2019 02:21:43 AM CDT
*/


/**
       *  Definitions for MO class RncFunction
       */
public interface RncFunction extends RncFunctionOperations, org.omg.GenericNetworkResourcesNRMDefs.ManagedFunction, org.omg.CORBA.portable.IDLEntity
{
  public static final String CLASS = "RncFunction";

  //
  public static final String rncFunctionId = "rncFunctionId";
  public static final String mcc = "mcc";
  public static final String mnc = "mnc";
  public static final String rncId = "rncId";
} // interface RncFunction
