package org.omg.UtranNetworkResourcesNRMDefs;


/**
* org.omg.UtranNetworkResourcesNRMDefs/RncFunctionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.UtranNetworkResourcesNRMDefs.idl
* jueves 5 de septiembre de 2019 02:21:43 AM CDT
*/


/**
       *  Definitions for MO class RncFunction
       */
public interface RncFunctionOperations  extends org.omg.GenericNetworkResourcesNRMDefs.ManagedFunctionOperations
{
} // interface RncFunctionOperations
