package org.omg.AlarmIRPNotifications;


/**
* org.omg.AlarmIRPNotifications/NotifyAlarmListRebuilt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.AlarmIRPNotifications.idl
* jueves 5 de septiembre de 2019 01:10:29 AM CDT
*/

public interface NotifyAlarmListRebuilt extends NotifyAlarmListRebuiltOperations, org.omg.NotificationIRPNotifications.Notify, org.omg.CORBA.portable.IDLEntity
{
  public static final String EVENT_TYPE = "notifyAlarmListRebuilt";
  public static final String REASON = org.omg.AlarmIRPConstDefs.AttributeNameValue.REASON;
  public static final String ALARM_LIST_ALIGNMENT_REQUIREMENT = org.omg.AlarmIRPConstDefs.AttributeNameValue.ALARM_LIST_ALIGNMENT_REQUIREMENT;
} // interface NotifyAlarmListRebuilt
