package org.omg.AlarmIRPNotifications;

/**
* org.omg.AlarmIRPNotifications/NotifyClearedAlarmHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.AlarmIRPNotifications.idl
* jueves 5 de septiembre de 2019 01:10:29 AM CDT
*/

public final class NotifyClearedAlarmHolder implements org.omg.CORBA.portable.Streamable
{
  public NotifyClearedAlarm value = null;

  public NotifyClearedAlarmHolder ()
  {
  }

  public NotifyClearedAlarmHolder (NotifyClearedAlarm initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = NotifyClearedAlarmHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    NotifyClearedAlarmHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return NotifyClearedAlarmHelper.type ();
  }

}
