package org.omg.FileTransferIRPSystem;


/**
* org.omg.FileTransferIRPSystem/FileDownloadIndication.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.FileTransferIRPSystem.idl
* jueves 5 de septiembre de 2019 02:18:30 AM CDT
*/

public final class FileDownloadIndication extends org.omg.CORBA.UserException
{
  public String reason = null;

  public FileDownloadIndication ()
  {
    super(FileDownloadIndicationHelper.id());
  } // ctor

  public FileDownloadIndication (String _reason)
  {
    super(FileDownloadIndicationHelper.id());
    reason = _reason;
  } // ctor


  public FileDownloadIndication (String $reason, String _reason)
  {
    super(FileDownloadIndicationHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class FileDownloadIndication
