package org.omg.FileTransferIRPSystem;


import org.omg.TimeBase.UtcT;

/**
* org.omg.FileTransferIRPSystem/FileTransferIRPOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.FileTransferIRPSystem.idl
* jueves 5 de septiembre de 2019 02:18:30 AM CDT
*/

public interface FileTransferIRPOperations 
{

  /*
      * IRPManager invoke this operation to get the files information
      */
  org.omg.FileTransferIRPConstDefs.Result list_available_files(short management_data_type, UtcT begin_time, UtcT end_time, org.omg.FileTransferIRPConstDefs.FileInfoListHolder file_info_list) throws ListAvailableFiles, InvalidTimes, org.omg.ManagedGenericIRPSystem.InvalidParameter;

  /*
      * IRPManager invoke this operation to indicate completion of downloading files to IRPAgent
      */
  org.omg.FileTransferIRPConstDefs.Result file_download_indication(org.omg.FileTransferIRPConstDefs.FileInfo[] file_info_list) throws FileDownloadIndication, InvalidFileInfoList, org.omg.ManagedGenericIRPSystem.OperationNotSupported;

  /**
      * Return the list of all supported FileTransferIRP versions.
      */
  String[] get_file_transfer_irp_versions() throws GetFileTransferIRPVersions;

  /**
      * Return the list of all supported operations and their supported
      * parameters for a specific FileTransferIRP version.
      */
  org.omg.ManagedGenericIRPConstDefs.Method[] get_file_transfer_irp_operations_profile(String irp_version) throws GetFileTransferIRPOperationsProfile, org.omg.ManagedGenericIRPSystem.OperationNotSupported, org.omg.ManagedGenericIRPSystem.InvalidParameter;

  /**
      * Return the list of all supported notifications and their supported
      * parameters for a specific FileTransferIRP version.
      */
  org.omg.ManagedGenericIRPConstDefs.Method[] get_file_transfer_irp_notifications_profile(String irp_version) throws GetFileTransferIRPNotificationsProfile, org.omg.ManagedGenericIRPSystem.OperationNotSupported, org.omg.ManagedGenericIRPSystem.InvalidParameter;
} // interface FileTransferIRPOperations
