package org.omg.FileTransferIRPSystem;


/**
* org.omg.FileTransferIRPSystem/GetFileTransferIRPVersions.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.FileTransferIRPSystem.idl
* jueves 5 de septiembre de 2019 02:18:30 AM CDT
*/

public final class GetFileTransferIRPVersions extends org.omg.CORBA.UserException
{
  public String reason = null;

  public GetFileTransferIRPVersions ()
  {
    super(GetFileTransferIRPVersionsHelper.id());
  } // ctor

  public GetFileTransferIRPVersions (String _reason)
  {
    super(GetFileTransferIRPVersionsHelper.id());
    reason = _reason;
  } // ctor


  public GetFileTransferIRPVersions (String $reason, String _reason)
  {
    super(GetFileTransferIRPVersionsHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class GetFileTransferIRPVersions
