package org.omg.FileTransferIRPSystem;


/**
* org.omg.FileTransferIRPSystem/InvalidFileInfoList.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.FileTransferIRPSystem.idl
* jueves 5 de septiembre de 2019 02:18:30 AM CDT
*/

public final class InvalidFileInfoList extends org.omg.CORBA.UserException
{
  public String reason = null;

  public InvalidFileInfoList ()
  {
    super(InvalidFileInfoListHelper.id());
  } // ctor

  public InvalidFileInfoList (String _reason)
  {
    super(InvalidFileInfoListHelper.id());
    reason = _reason;
  } // ctor


  public InvalidFileInfoList (String $reason, String _reason)
  {
    super(InvalidFileInfoListHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class InvalidFileInfoList
