package org.omg.EPIRPNotifications;

/**
* org.omg.EPIRPNotifications/notifyIRPInfoChangesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.EPIRPNotifications.idl
* jueves 5 de septiembre de 2019 02:17:15 AM CDT
*/

public final class notifyIRPInfoChangesHolder implements org.omg.CORBA.portable.Streamable
{
  public notifyIRPInfoChanges value = null;

  public notifyIRPInfoChangesHolder ()
  {
  }

  public notifyIRPInfoChangesHolder (notifyIRPInfoChanges initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = notifyIRPInfoChangesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    notifyIRPInfoChangesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return notifyIRPInfoChangesHelper.type ();
  }

}
