package org.omg.CSIRPNotifications;

/**
* org.omg.CSIRPNotifications/notifyHeartbeatHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CSIRPNotifications.idl
* jueves 5 de septiembre de 2019 02:16:55 AM CDT
*/


/**
   *  Constant definitions for the FileReady notification
   */
public final class notifyHeartbeatHolder implements org.omg.CORBA.portable.Streamable
{
  public notifyHeartbeat value = null;

  public notifyHeartbeatHolder ()
  {
  }

  public notifyHeartbeatHolder (notifyHeartbeat initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = notifyHeartbeatHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    notifyHeartbeatHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return notifyHeartbeatHelper.type ();
  }

}
