package org.omg.ManagedGenericIRPSystem;


/**
* org.omg.ManagedGenericIRPSystem/OperationNotSupported.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.ManagedGenericIRPSystem.idl
* jueves 5 de septiembre de 2019 01:58:56 AM CDT
*/


/*
   Exception thrown when an unsupported optional method is called.
   */
public final class OperationNotSupported extends org.omg.CORBA.UserException
{

  public OperationNotSupported ()
  {
    super(OperationNotSupportedHelper.id());
  } // ctor


  public OperationNotSupported (String $reason)
  {
    super(OperationNotSupportedHelper.id() + "  " + $reason);
  } // ctor

} // class OperationNotSupported
