package org.omg.CosEventChannelAdmin;


/**
* org.omg.CosEventChannelAdmin/SupplierAdmin.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CosEventChannelAdmin.idl
* jueves 5 de septiembre de 2019 02:15:23 AM CDT
*/

public interface SupplierAdmin extends SupplierAdminOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SupplierAdmin
