package org.omg.CosEventChannelAdmin;


/**
* org.omg.CosEventChannelAdmin/SupplierAdminPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CosEventChannelAdmin.idl
* jueves 5 de septiembre de 2019 02:15:23 AM CDT
*/

public abstract class SupplierAdminPOA extends org.omg.PortableServer.Servant
 implements SupplierAdminOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("obtain_push_consumer", new Integer (0));
    _methods.put ("obtain_pull_consumer", new Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    Integer __method = (Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // org.omg.CosEventChannelAdmin/SupplierAdmin/obtain_push_consumer
       {
         ProxyPushConsumer $result = null;
         $result = this.obtain_push_consumer ();
         out = $rh.createReply();
         ProxyPushConsumerHelper.write (out, $result);
         break;
       }

       case 1:  // org.omg.CosEventChannelAdmin/SupplierAdmin/obtain_pull_consumer
       {
         ProxyPullConsumer $result = null;
         $result = this.obtain_pull_consumer ();
         out = $rh.createReply();
         ProxyPullConsumerHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:omg.org/CosEventChannelAdmin/SupplierAdmin:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public SupplierAdmin _this() 
  {
    return SupplierAdminHelper.narrow(
    super._this_object());
  }

  public SupplierAdmin _this(org.omg.CORBA.ORB orb) 
  {
    return SupplierAdminHelper.narrow(
    super._this_object(orb));
  }


} // class SupplierAdminPOA
