package org.omg.CosEventChannelAdmin;

/**
* org.omg.CosEventChannelAdmin/TypeErrorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.CosEventChannelAdmin.idl
* jueves 5 de septiembre de 2019 02:15:22 AM CDT
*/

public final class TypeErrorHolder implements org.omg.CORBA.portable.Streamable
{
  public TypeError value = null;

  public TypeErrorHolder ()
  {
  }

  public TypeErrorHolder (TypeError initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TypeErrorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TypeErrorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TypeErrorHelper.type ();
  }

}
