package org.omg.TimeBase;

import org.omg.TimeBase.IntervalT;
import org.omg.TimeBase.IntervalTHelper;

/**
* org.omg.TimeBase/IntervalTHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.TimeBase.idl
* jueves 5 de septiembre de 2019 02:04:35 AM CDT
*/

public final class IntervalTHolder implements org.omg.CORBA.portable.Streamable
{
  public IntervalT value = null;

  public IntervalTHolder ()
  {
  }

  public IntervalTHolder (IntervalT initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IntervalTHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IntervalTHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IntervalTHelper.type ();
  }

}
