package org.omg.TimeBase;

import org.omg.TimeBase.UtcT;
import org.omg.TimeBase.UtcTHelper;

/**
* org.omg.TimeBase/UtcTHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.TimeBase.idl
* jueves 5 de septiembre de 2019 02:04:35 AM CDT
*/

public final class UtcTHolder implements org.omg.CORBA.portable.Streamable
{
  public UtcT value = null;

  public UtcTHolder ()
  {
  }

  public UtcTHolder (UtcT initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = UtcTHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    UtcTHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return UtcTHelper.type ();
  }

}
