package org.omg.KernelCmNotifications.MODeletionPackage;


/**
* org.omg.KernelCmNotifications/MODeletionPackage/AttributeValuesHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.KernelCmNotifications.idl
* jueves 5 de septiembre de 2019 02:20:05 AM CDT
*/


/**
          * This information mapped into the remainder_of_body 
          * in the StructuredEvent 
          */
abstract public class AttributeValuesHelper
{
  private static String  _id = "IDL:3gppsa5.org/KernelCmNotifications/MODeletion/AttributeValues:1.0";

  public static void insert (org.omg.CORBA.Any a, org.omg.KernelCmConstDefs.MOAttribute[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.omg.KernelCmConstDefs.MOAttribute[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.KernelCmConstDefs.MOAttributeHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (org.omg.KernelCmConstDefs.MOAttributeSetHelper.id (), "MOAttributeSet", __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (AttributeValuesHelper.id (), "AttributeValues", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.omg.KernelCmConstDefs.MOAttribute[] read (org.omg.CORBA.portable.InputStream istream)
  {
    org.omg.KernelCmConstDefs.MOAttribute value[] = null;
    value = org.omg.KernelCmConstDefs.MOAttributeSetHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.omg.KernelCmConstDefs.MOAttribute[] value)
  {
    org.omg.KernelCmConstDefs.MOAttributeSetHelper.write (ostream, value);
  }

}
