package org.omg.TDDNRMAttributeTypes;


/**
* org.omg.TDDNRMAttributeTypes/TimeSlotStatusTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.UtranNetworkResourcesNRMDefs.idl
* jueves 5 de septiembre de 2019 02:21:44 AM CDT
*/

abstract public class TimeSlotStatusTypeHelper
{
  private static String  _id = "IDL:3gppsa5.org/org.omg.TDDNRMAttributeTypes/TimeSlotStatusType:1.0";

  public static void insert (org.omg.CORBA.Any a, TimeSlotStatusType that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static TimeSlotStatusType extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (TimeSlotStatusTypeHelper.id (), "TimeSlotStatusType", new String[] { "Active", "Not_Active"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static TimeSlotStatusType read (org.omg.CORBA.portable.InputStream istream)
  {
    return TimeSlotStatusType.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, TimeSlotStatusType value)
  {
    ostream.write_long (value.value ());
  }

}
