package org.omg.TDDNRMAttributeTypes;

/**
* org.omg.TDDNRMAttributeTypes/TimeSlotConfigStructTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.UtranNetworkResourcesNRMDefs.idl
* jueves 5 de septiembre de 2019 02:21:44 AM CDT
*/

public final class TimeSlotConfigStructTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public TimeSlotConfigStructType value = null;

  public TimeSlotConfigStructTypeHolder ()
  {
  }

  public TimeSlotConfigStructTypeHolder (TimeSlotConfigStructType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TimeSlotConfigStructTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TimeSlotConfigStructTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TimeSlotConfigStructTypeHelper.type ();
  }

}
