package org.omg.TDDNRMAttributeTypes;


/**
* org.omg.TDDNRMAttributeTypes/TimeSlotConfigStructType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.UtranNetworkResourcesNRMDefs.idl
* jueves 5 de septiembre de 2019 02:21:44 AM CDT
*/

public final class TimeSlotConfigStructType implements org.omg.CORBA.portable.IDLEntity
{
  public short timeSlotId = (short)0;
  public TimeSlotDirectionType timeSlotDirection = null;
  public TimeSlotStatusType timeSlotStatus = null;

  public TimeSlotConfigStructType ()
  {
  } // ctor

  public TimeSlotConfigStructType (short _timeSlotId, TimeSlotDirectionType _timeSlotDirection, TimeSlotStatusType _timeSlotStatus)
  {
    timeSlotId = _timeSlotId;
    timeSlotDirection = _timeSlotDirection;
    timeSlotStatus = _timeSlotStatus;
  } // ctor

} // class TimeSlotConfigStructType
