package org.omg.TDDNRMAttributeTypes;


/**
* org.omg.TDDNRMAttributeTypes/TimeSlotConfigStructTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.UtranNetworkResourcesNRMDefs.idl
* jueves 5 de septiembre de 2019 02:21:44 AM CDT
*/

abstract public class TimeSlotConfigStructTypeHelper
{
  private static String  _id = "IDL:3gppsa5.org/org.omg.TDDNRMAttributeTypes/TimeSlotConfigStructType:1.0";

  public static void insert (org.omg.CORBA.Any a, TimeSlotConfigStructType that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static TimeSlotConfigStructType extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[0] = new org.omg.CORBA.StructMember (
            "timeSlotId",
            _tcOf_members0,
            null);
          _tcOf_members0 = TimeSlotDirectionTypeHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "timeSlotDirection",
            _tcOf_members0,
            null);
          _tcOf_members0 = TimeSlotStatusTypeHelper.type ();
          _members0[2] = new org.omg.CORBA.StructMember (
            "timeSlotStatus",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (TimeSlotConfigStructTypeHelper.id (), "TimeSlotConfigStructType", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static TimeSlotConfigStructType read (org.omg.CORBA.portable.InputStream istream)
  {
    TimeSlotConfigStructType value = new TimeSlotConfigStructType ();
    value.timeSlotId = istream.read_short ();
    value.timeSlotDirection = TimeSlotDirectionTypeHelper.read (istream);
    value.timeSlotStatus = TimeSlotStatusTypeHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, TimeSlotConfigStructType value)
  {
    ostream.write_short (value.timeSlotId);
    TimeSlotDirectionTypeHelper.write (ostream, value.timeSlotDirection);
    TimeSlotStatusTypeHelper.write (ostream, value.timeSlotStatus);
  }

}
