package org.omg.GenericNetworkResourcesNRMDefs;


/**
* org.omg.GenericNetworkResourcesNRMDefs/ManagementNode.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.GenericNetworkResourcesNRMDefs.idl
* jueves 5 de septiembre de 2019 02:19:12 AM CDT
*/


/**
       *  Definitions for MO class ManagementNode
       */
public interface ManagementNode extends ManagementNodeOperations, Top, org.omg.CORBA.portable.IDLEntity
{
  public static final String CLASS = "ManagementNode";

  //
  public static final String managementNodeId = "managementNodeId";
  public static final String userLabel = "userLabel";
  public static final String vendorName = "vendorName";
  public static final String userDefinedState = "userDefinedState";
  public static final String locationName = "locationName";
  public static final String managedElements = "managedElements";
  public static final String swVersion = "swVersion";
} // interface ManagementNode
