package org.omg.GenericNetworkResourcesNRMDefs;


/**
* org.omg.GenericNetworkResourcesNRMDefs/ManagementNodeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.GenericNetworkResourcesNRMDefs.idl
* jueves 5 de septiembre de 2019 02:19:12 AM CDT
*/


/**
       *  Definitions for MO class ManagementNode
       */
public interface ManagementNodeOperations  extends TopOperations
{
} // interface ManagementNodeOperations
