package org.omg.GenericNetworkResourcesNRMDefs;

/**
* org.omg.GenericNetworkResourcesNRMDefs/SubNetworkHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.GenericNetworkResourcesNRMDefs.idl
* jueves 5 de septiembre de 2019 02:19:11 AM CDT
*/


/**
       *  Definitions for MO class SubNetwork
       */
public final class SubNetworkHolder implements org.omg.CORBA.portable.Streamable
{
  public SubNetwork value = null;

  public SubNetworkHolder ()
  {
  }

  public SubNetworkHolder (SubNetwork initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SubNetworkHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SubNetworkHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SubNetworkHelper.type ();
  }

}
