package org.omg.GenericNetworkResourcesNRMDefs;


/**
* org.omg.GenericNetworkResourcesNRMDefs/SubNetwork.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.GenericNetworkResourcesNRMDefs.idl
* jueves 5 de septiembre de 2019 02:19:11 AM CDT
*/


/**
       *  Definitions for MO class SubNetwork
       */
public interface SubNetwork extends SubNetworkOperations, Top, org.omg.CORBA.portable.IDLEntity
{
  public static final String CLASS = "SubNetwork";

  //
  public static final String subNetworkId = "subNetworkId";
  public static final String dnPrefix = "dnPrefix";
  public static final String userLabel = "userLabel";
  public static final String userDefinedNetworkType = "userDefinedNetworkType";
  public static final String setOfMcc = "setOfMcc";
} // interface SubNetwork
