package org.omg.EPIRPSystem;


/**
* org.omg.EPIRPSystem/EPIRPHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.EPIRPSystem.idl
* jueves 5 de septiembre de 2019 02:17:21 AM CDT
*/


/*
  */
abstract public class EPIRPHelper
{
  private static String  _id = "IDL:3gppsa5.org/EPIRPSystem/EPIRP:1.0";

  public static void insert (org.omg.CORBA.Any a, EPIRP that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static EPIRP extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (EPIRPHelper.id (), "EPIRP");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static EPIRP read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_EPIRPStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, EPIRP value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static EPIRP narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof EPIRP)
      return (EPIRP)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _EPIRPStub stub = new _EPIRPStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static EPIRP unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof EPIRP)
      return (EPIRP)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _EPIRPStub stub = new _EPIRPStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
