package org.omg.EPIRPSystem;


/**
* org.omg.EPIRPSystem/GetEPIRPOperationsProfile.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.EPIRPSystem.idl
* jueves 5 de septiembre de 2019 02:17:21 AM CDT
*/

public final class GetEPIRPOperationsProfile extends org.omg.CORBA.UserException
{
  public String reason = null;

  public GetEPIRPOperationsProfile ()
  {
    super(GetEPIRPOperationsProfileHelper.id());
  } // ctor

  public GetEPIRPOperationsProfile (String _reason)
  {
    super(GetEPIRPOperationsProfileHelper.id());
    reason = _reason;
  } // ctor


  public GetEPIRPOperationsProfile (String $reason, String _reason)
  {
    super(GetEPIRPOperationsProfileHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class GetEPIRPOperationsProfile
