package org.omg.EPIRPSystem;

/**
* org.omg.EPIRPSystem/GetIRPReferenceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.EPIRPSystem.idl
* jueves 5 de septiembre de 2019 02:17:21 AM CDT
*/

public final class GetIRPReferenceHolder implements org.omg.CORBA.portable.Streamable
{
  public GetIRPReference value = null;

  public GetIRPReferenceHolder ()
  {
  }

  public GetIRPReferenceHolder (GetIRPReference initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GetIRPReferenceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GetIRPReferenceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GetIRPReferenceHelper.type ();
  }

}
