package org.omg.EPIRPSystem;

/**
* org.omg.EPIRPSystem/InvalidIRPVersionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.EPIRPSystem.idl
* jueves 5 de septiembre de 2019 02:17:21 AM CDT
*/

public final class InvalidIRPVersionHolder implements org.omg.CORBA.portable.Streamable
{
  public InvalidIRPVersion value = null;

  public InvalidIRPVersionHolder ()
  {
  }

  public InvalidIRPVersionHolder (InvalidIRPVersion initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = InvalidIRPVersionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    InvalidIRPVersionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return InvalidIRPVersionHelper.type ();
  }

}
