package org.omg.EPIRPSystem;


/**
* org.omg.EPIRPSystem/ReleaseIRPReference.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.EPIRPSystem.idl
* jueves 5 de septiembre de 2019 02:17:21 AM CDT
*/

public final class ReleaseIRPReference extends org.omg.CORBA.UserException
{
  public String reason = null;

  public ReleaseIRPReference ()
  {
    super(ReleaseIRPReferenceHelper.id());
  } // ctor

  public ReleaseIRPReference (String _reason)
  {
    super(ReleaseIRPReferenceHelper.id());
    reason = _reason;
  } // ctor


  public ReleaseIRPReference (String $reason, String _reason)
  {
    super(ReleaseIRPReferenceHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class ReleaseIRPReference
