package org.omg.FileTransferIRPNotifications;

/**
* org.omg.FileTransferIRPNotifications/NotifyFilePreparationErrorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org.omg.FileTransferIRPNotifications.idl
* jueves 5 de septiembre de 2019 02:17:39 AM CDT
*/


/**
   * Constant definitions for the FilePreparationError notification
   */
public final class NotifyFilePreparationErrorHolder implements org.omg.CORBA.portable.Streamable
{
  public NotifyFilePreparationError value = null;

  public NotifyFilePreparationErrorHolder ()
  {
  }

  public NotifyFilePreparationErrorHolder (NotifyFilePreparationError initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = NotifyFilePreparationErrorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    NotifyFilePreparationErrorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return NotifyFilePreparationErrorHelper.type ();
  }

}
